### ISSUE TITLE
 Build failed on Parabola

### ISSUE THREAD

**Issue by elch01** [ungoogled-software/ungoogled-chromium-archlinux#101]
When i try to build i get a clang unknown argument error.

`FAILED: obj/base/third_party/xdg_mime/xdg_mime/xdgmimealias.o 
clang -MMD -MF obj/base/third_party/xdg_mime/xdg_mime/xdgmimealias.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLANG_REVISION=\"n356902-4e813bbd-1\" -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -fprofile-sample-use=../../chrome/android/profiles/afdo.prof -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -flto=thin -fsplit-lto-unit -fwhole-program-vtables -m64 -march=x86-64 -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fsanitize=cfi-vcall -fsanitize-blacklist=../../tools/cfi/blacklist.txt -fsanitize=cfi-icall -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wno-unused-variable -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-max-tokens -std=c11 -Wno-implicit-fallthrough -D_FORTIFY_SOURCE=2 -D__DATE__=  -D__TIME__=  -D__TIMESTAMP__= -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fvar-tracking-assignments -fdebug-prefix-map=/home/esd/Downloads/ungoogled-chromium-archlinux-master/src=/usr/src/debug   -Wno-builtin-macro-redefined   -Wno-unknown-warning-option -c ../../base/third_party/xdg_mime/xdgmimealias.c -o obj/base/third_party/xdg_mime/xdg_mime/xdgmimealias.o
clang: error: unknown argument: '-fvar-tracking-assignments'
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
`

Clang version: 10.0.1-1
Linux version: linux-libre 5.8.5-1

Any help would be much appreciated, thanks!

**Comment by jstkdng** [comment]
The only place those flags exist is in /etc/makepkg.conf
![image](https://user-images.githubusercontent.com/52050345/92929938-f7a52d80-f406-11ea-9c20-049489c93894.png)
and supposedly, those are used when you build with the debug flag. Those flags only work with GCC and not with clang. Maybe your CC/CXX variable has that flag in them, if so, remove it.

**Comment by elch01** [comment]
Removing the flag works.
Builds perfectly, thanks.
