### ISSUE TITLE
building fails with "FAILED: obj/content/browser/browser/web_bluetooth_service_impl.o"

### ISSUE THREAD

**Issue by gerryd** [ungoogled-software/ungoogled-chromium-archlinux#106]
I don't seem to be able to build the latest releases. 

These are the (shortened) last few lines of the build log:

    [30966/42075] CXX obj/content/browser/browser/web_bluetooth_service_impl.o
    FAILED: obj/content/browser/browser/web_bluetooth_service_impl.o
    clang++ -MMD -MF obj/content/browser/browser/web_bluetooth_service_impl.o.d -DUSE_UDEV <..> -c ../../content/browser/bluetooth/web_bluetooth_service_impl.cc -o obj/content/browser/browser/web_bluetooth_service_impl.o
    [30977/42075] CXX obj/content/browser/browser/target_auto_attacher.o
    ninja: build stopped: subcommand failed.
    ==> ERROR: A failure occurred in build().
        Aborting...

The full build log is attached.

Would you have any pointers as to how I could fix this?

Thanks!

[build.log](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/files/5535035/build.log)

**Comment by wchen342** [comment]
If no other error message then the most likely cause is insufficient memory.

**Comment by gerryd** [comment]
Thanks for the pointer! I have increased the memory on my build machine from 12 to 24GiB. Let's see if that fixes the issue. I will report back with my findings.

**Comment by gerryd** [comment]
Build completed. Many thanks for your help!
