### ISSUE TITLE
New ICU v68 Breaks Chromium 87.0.4280.88

### ISSUE THREAD

**Issue by v00v** [ungoogled-software/ungoogled-chromium-archlinux#109]
ERROR: /usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.67: cannot open shared object file: No such file or directory

Versions:
icu-68.2-1-x86_64
harfbuzz-icu-2.7.2-3-x86_64
harfbuzz-icu-2.7.2-3-x86_64

Please recompile Ungoogled Chromium. Thank you!

**Comment by v00v** [comment]
Workaround for now > https://download.opensuse.org/repositories/home:/justkidding:/arch/standard/x86_64/ungoogled-chromium-87.0.4280.88-3-x86_64.pkg.tar.zst.mirrorlist

**Comment by mcstrugs** [comment]
Thanks for the info, I'll compile the updated AUR version and post in in the binaries repo.

**Comment by jstkdng** [comment]
it should be working now. closing.

**Comment by v00v** [comment]
@mcstrugs when might this happen?

@jstkdng No its is not. Version 87.0.4280.88-1 still dosn'twork. The link I provided is for 3rd-party binary built by some OpenSuse user. We need an official release here.

**Comment by jstkdng** [comment]
@v00v 
That third party opensuse user is literally me, lol

**Comment by v00v** [comment]
@jstkdng Oh LOL Good to know ^_^
