### ISSUE TITLE
New ICU v68 Breaks Chromium 87.0.4280.88

### ISSUE THREAD

**Issue by v00v** [ungoogled-software/ungoogled-chromium-archlinux#110]
**CLOSED TOO SOON!** https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/109

I still get the same error while tryingto install;
``ungoogled-chromium-87.0.4280.88-1-x86_64.pkg.tar.zst`` binary.

Error I get;
``usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.67: cannot open shared object file: No such file or directory``

This is most likely due to new ICU package updates; ``harfbuzz-2.7.2``, ``harfbuzz-icu-2.7.2``, and ``icu-68.2``
 
Also compiling "ungoogled-chromium" package yourself takes at least 30gb of space. Not to mantion a lot longer if compiled on older computer.

**Comment by jstkdng** [comment]
I've released a binary here built from the github action, you could consider it "official"
https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/tag/87.0.4280.88-3
please test it

**Comment by v00v** [comment]
Confirmed works! Thank you!
