### ISSUE TITLE
Improvement: Add PKGBUILD dependencies to correct versions of icu and re2

### ISSUE THREAD

**Issue by cookiengineer** [ungoogled-software/ungoogled-chromium-archlinux#111]
When installing the Ungoogled Chromium package on Arch Linux, and updating the system while the `ungoogled-chromium` package still has no update; it will break Chromium due to two different reasons:

1. the `icu` package isn't added as a specific versioned dependency, so it is assumed that e.g. icu99 will be compatible with icu98; which is not the case because ungoogled-chromium builds are incompatible with another subversion of icu.
2. the `re2` package isn't added as a specific versioned dependency (e.g. `libre2.so.8` is required, but `libre2.so.9` is currently shipped upstream).

So I guess I have an improvement request(?) now regarding this to add the subversions correctly to the PKGBUILD file, so that the packages are not upgraded automatically. Accessing and searching the Arch Linux Archive for an old package isn't easy when you have no Browser available :sweat:

**Comment by cookiengineer** [comment]
I've added a Pull Request regarding this:

https://github.com/ungoogled-software/ungoogled-chromium-archlinux/pull/112

**Comment by jstkdng** [comment]
No.
This issue is not just with re2 or icu as this issue happened with libvpx and libjsoncpp.
The best solution would be to do a static build or use guix/appimage.

**Comment by cookiengineer** [comment]
But, using chromium for over 8 years now; and having compiled chromium myself before using ungoogled-chromium; I can with absolute certain say that only those specific two libraries break with updates. Every single time.

While I agree that embedding static libraries would be _a_ solution, I still think that re2 and icu are the only libraries that are not downwards compatible; so every subminor release of those libraries will break its downstream dependencies. Every other library that `ldd chromium` and `ldd chromedriver` shows are semantically correctly versioned; and will not break if I update e.g. v2.1.x to v2.2.x of the same library.
