### ISSUE TITLE
Detection for common rebuild causes

### ISSUE THREAD

**Issue by braewoods** [ungoogled-software/ungoogled-chromium-archlinux#118]
Due to how Arch differs from other distributions we routinely see a need for rebuilds for library ABI breakages. Is there a way we can add a scheduled task to check whether our OBS package needs to be rebuilt or so?

I could probably script something together using an Arch workflow but this needs to be scheduled instead of being tied to repository events. We could run it once a day or so to detect problems and then maybe report them by opening an issue or so.

**Comment by braewoods** [comment]
The motivation behind this is to be able to detect them instead of having to wait for user reports of breakages so we can get onto fixing it sooner.

**Comment by braewoods** [comment]
Ok so apparently there is a way to do this.

**Comment by v00v** [comment]
This is what I said too LOL :-) @ https://github.com/Eloston/ungoogled-chromium/issues/1492
You could easily script something using bash or python and use something like cronie to check daily.

**Comment by jstkdng** [comment]
The OBS rebuilds on every dependency upgrade so this should't be needed.
It also has its own repositories so it sometimes happens that a new lib isn't yet available for the OBS.

**Comment by braewoods** [comment]
Well, I turned that off in our OBS repository because it was triggering unnecessary rebuilds.

**Comment by braewoods** [comment]
I'll re-enable that for Arch only since it's the only one where this would be useful.

**Comment by networkException** [comment]
I may look into github actions cron, that could just try chromium --help with the obs build every once in a while

**Comment by braewoods** [comment]
It's somewhat moot though until we can find out why it's not building.

**Comment by networkException** [comment]
yes indeed. I will try to finish the work on my docker branch today and look into a build fix then. This is taking more time than I thought

**Comment by unbranched** [comment]
Ping, no production data again.

**Comment by networkException** [comment]
no what?

**Comment by unbranched** [comment]
I was speaking about this:
https://software.opensuse.org//download.html?project=home%3Aungoogled_chromium&package=ungoogled-chromium-arch

Sorry for being that cryptic, I actually wanted to comment on [issue 135](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/135) on a different browser tab, my bad.

**Comment by networkException** [comment]
Oh I see... Maybe its just the webinterface? At least pacman seems to be able to fetch the database on my machine

**Comment by networkException** [comment]
I will close this for now, the tigher release cycle makes rebuilds due to linking issues less likely and if its required non the less it can be done manually.
