### ISSUE TITLE
Can't run latest build from OBS repository on Manjaro

### ISSUE THREAD

**Issue by blipk** [ungoogled-software/ungoogled-chromium-archlinux#119]
Experiencing this issue here: https://github.com/Eloston/ungoogled-chromium/issues/1492

I'm experiencing this issue using the latest OBS Arch Linux repository build (89.0.4389.114-2)

/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.69: cannot open shared object file: No such file or directory

I tried creating a symbolic link, then I get
/usr/lib/chromium/chromium: error while loading shared libraries: libicuuc.so.69: cannot open shared object file: No such file or directory

So I linked that as well, now I get:
/usr/lib/chromium/chromium: symbol lookup error: /usr/lib/chromium/chromium: undefined symbol: _ZN6icu_698TimeZone13createDefaultEv

Are there still issues with the build in OBS?

**Comment by braewoods** [comment]
OBS tracks the upstream Arch repository so derivatives such as Manjaro that are behind in their packages cannot be guaranteed to work. There's nothing we can really do about this due to Arch's volatility due to being rolling release. You'll have to build it yourself if you want it to be guaranteed to work for Manjaro.

**Comment by braewoods** [comment]
Essentially if I rebuild it for Arch it won't work for Manjaro anymore but if I rebuild it for Manjaro it won't work for Arch anymore.

**Comment by blipk** [comment]
:(

I tried the AUR repository but the build takes 12+ hours on my machine.
Thanks anyway, I guess I'll just use the older version in AppImage until the repositories catch up.

**Comment by braewoods** [comment]
If this matters so much to you, I'd suggest using our Debian or Ubuntu derivatives instead. This is a non-issue since they are a stable foundation.

**Comment by blipk** [comment]
I wasn't aware that Debian packages could be installed on Arch derivatives? I'm looking here https://github.com/ungoogled-software/ungoogled-chromium-debian and it seems those OBS repositories serve up .deb packages.

It's not a huge issue, I can make do with the AppImage in the meantime.

**Comment by braewoods** [comment]
They can't. I'm just suggesting you switch distributions if you can afford to do so. It's things like this that made me leave Arch behind for a more stable ecosystem.

**Comment by blipk** [comment]
Thanks, if I have more issues in the future I will consider it.
Feel free to close this.

**Comment by braewoods** [comment]
Linux Mint, which is derived from Ubuntu LTS releases, is a decent choice. They strip out the worst stuff that people usually hate about canonical and regular Ubuntu desktop flavors.
