### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by braewoods** [ungoogled-software/ungoogled-chromium-archlinux#123]
I've tested ours and Arch's official packaging and they all fail with the same error. The only common factor I can see is that these builds are all in freshly created containers or other environments. I'm assuming Arch only succeeds due to using an older installation to build.

@networkException You have any thoughts on this issue? I'm surprised no one has opened a bug on the Arch bug tracker given that it also impacts their official package too.

**Comment by networkException** [comment]
Interesting, where did you observe the issues (meaning just obs or locally and / or in docker)? 

I've been reworking the CI pipeline on a local branch, basically building a docker image out of all built files required for a given versions (PKGBUILD, patches, chromium tar) and using that as a base for actually building, for the last day and although I haven't let ninja run further than ~3k objects it didn't complain really.

**Comment by braewoods** [comment]
AFAIK OBS creates a fresh container image for each build. This has never been an issue for the other distributions we build on OBS and until Chromium 90 was not an issue on Arch either. It's why I suspect it's some kind of upstream issue because of how volatile Arch is even with all their precautions.

**Comment by braewoods** [comment]
The error I see is this: `flatc failed with exit code -5`

And the AUR users also have the same issue. So it seems to be an issue for more than just us. See here in the comments:
https://aur.archlinux.org/packages/ungoogled-chromium

**Comment by nikolowry** [comment]
> The error I see is this: `flatc failed with exit code -5`
> 
> And the AUR users also have the same issue. So it seems to be an issue for more than just us. See here in the comments:
> https://aur.archlinux.org/packages/ungoogled-chromium

Additional context to hopefully helps with investigating:
- Same error when using the latest version of `third_party/llvm-build` (emulated how `chromium-dev` does  it: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chromium-dev#n467)
- I can successfully build the latest Bromite release, v90.0.4430.92 with my `bromite-builder` utility script (https://github.com/nikolowry/bromite-builder/). It uses `gclient` and the toolchain provided by Chromium.

**Comment by nikolowry** [comment]
I saw `chromium` (https://archlinux.org/packages/extra/x86_64/chromium/) had 4 updates over the past 16 days, but trying to build locally with `makepkg` results in the same error:
```
[5816/48013] ACTION //extensions/browser/api/declarative_net_request/flat:extension_ruleset_gen(//build/toolchain/linux/unbundle:default)
FAILED: gen/extensions/browser/api/declarative_net_request/flat/extension_ruleset_generated.h 
python ../../build/gn_run_binary.py flatc -c --keep-prefix -o gen/extensions/browser/api/declarative_net_request/flat -I ../../ ../../extensions/browser/api/declarative_net_request/flat/extension_ruleset.fbs
flatc failed with exit code -5
[5833/48013] ACTION //third_party/blink/renderer/bindings:generate_bindings_all(//build/toolchain/linux/unbundle:default)
ninja: build stopped: subcommand failed.
```

@foutrelis and @felixonmars any insights you could provide?

**Comment by braewoods** [comment]
I noticed that Arch also provides flatc in their flatbuffers or so package. Maybe we can switch to using the system flatc to get past this issue.

**Comment by Area51Kacz** [comment]
I'd try all options >_

here he adds some flags
https://github.com/archlinux/svntogit-packages/blob/master/chromium/trunk/PKGBUILD

`    'rtc_use_pipewire=true'`
`    'rtc_pipewire_version="0.3"' # will be the default in Chromium 90`


And added flatbuffers and pipewire at makedepends   
https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium/ungoogled-chromium-arch

**Comment by networkException** [comment]
Part of the problem seems to actually be the flatc binary provided in the chromium sources. I added a quick hack to `build/gn_run_binary.py`
```python
if args[0] == './flatc':
    args[0] = '/usr/bin/flatc';
```
that makes it build further. Both binaries output `flatc version 1.12.0`

**Comment by braewoods** [comment]
That's built on the fly for Debian too but it doesn't error out there despite using the same sources. So either there's enough differences in the patches to break flatc or there's a toolchain issue here. We patch Arch less than we patch Debian so I would suspect the latter is more likely.

**Comment by Area51Kacz** [comment]
`		third_party/flatbuffers
`

On gentoo theres a line talking about flatbuffers https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/chromium/chromium-90.0.4430.93.ebuild

**Comment by Ahrotahn** [comment]
I believe I figured it out:  
Remove `-fcf-protection` from your makepkg.conf CFLAGS and start a clean build.  

---

I actually didn't have any issues building and didn't notice this until @braewoods commented about it on the main issue tracker.  
Clean builds of both ungoogled and regular chromium built fine for me, so I set up a container this morning and finally encountered the issue.  

flatc is being built and isn't shipped as a binary, so it had to be compiling differently somehow.  
I ran strace on flatc and found that it was encountering a breakpoint and exiting with a SIGTRAP which is really odd.  
I checked gdb to find where this was happening but could not find anything in the code that would cause this.  

After thinking further on this I realized that something had to have changed with arch as the code was identical in both the container and outside.  Since I was running the same kernel and software versions the only thing that made sense was a config difference.  I ran pacdiff and sure enough there was a pacnew for makepkg.conf that I hadn't yet applied.  

[There was an update to pacman recently that introduced some new flags, including -fcf-protection](https://github.com/archlinux/svntogit-packages/commit/a790c389cb0fd2ddd35e1f581ee337f6891801fc#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a).  This explains why new installs encountered the issue while some with existing installs were not.

**Comment by networkException** [comment]
That would explain why the ci pipeline doesn't break either, it uses a custom config file

**Comment by jstkdng** [comment]
yeah, it uses an old makepkg.conf
now how to ship this change to everyone without telling them to modify their makepkg.conf file?

**Comment by Ahrotahn** [comment]
The PKGBUILD could be updated to include `CFLAGS=${CFLAGS/-fcf-protection}` and `CXXFLAGS=${CXXFLAGS/-fcf-protection}`.

**Comment by jstkdng** [comment]
I'm trying something like that on my side but it keeps failing on the OBS

**Comment by braewoods** [comment]
Applied the workaround and launched a test build.

**Comment by jstkdng** [comment]
![image](https://user-images.githubusercontent.com/52050345/116823201-c7063580-ab48-11eb-8b2d-b6d15205cfb5.png)
It failed for me again, maybe more flags have to be removed

**Comment by bsdice** [comment]
Man, this bug was driving me nuts. Thanks guys or gals for the helpful tips. I reverted the flag changes and trying a build now. Hat-tip to @Ahrotahn for finding the flag change. I wonder what else might be breaking silently with this change. After flatc I saw protoc from protobuf package also failing during package build. Maintainers are in for a surprise on next bulk rebuild or version bump... Arch is on wrong track here imho. What every Linux desktop user needs in absolutely good working order is three things: Kernel, systemd, web browser. Just can't break any of that.

For reference here is the RFC that recommended the build flag change: https://gitlab.archlinux.org/archlinux/rfcs/-/blob/master/rfcs/0003-buildflags.rst#specification

Relevant commit for makepkg.conf: https://github.com/archlinux/svntogit-packages/commit/a790c389cb0fd2ddd35e1f581ee337f6891801fc#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a

**Comment by jstkdng** [comment]
at this point I'm inclined to hard set our CFLAGS and ignore system ones.

**Comment by braewoods** [comment]
Doesn't really matter to me what we do but I do want a solution. But given that this started from an upstream change I suspect we're going to have a lot of trouble ahead for us.

**Comment by Area51Kacz** [comment]
@jstkdng @braewoods Imho.. we could extract (some) inspiration from gentoo _(jump to line 255) _ >)  

https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/chromium/chromium-90.0.4430.93.ebuild

```
	local keeplibs=(
		third_party/flatbuffers
```

**Comment by Area51Kacz** [comment]
```
[  647s] [6614/47493] ACTION //extensions/browser/api/declarative_net_request/flat:extension_ruleset_gen(//build/toolchain/linux/unbundle:default)
[  647s] FAILED: gen/extensions/browser/api/declarative_net_request/flat/extension_ruleset_generated.h 
[  647s] python2 ../../build/gn_run_binary.py flatc -c --keep-prefix -o gen/extensions/browser/api/declarative_net_request/flat -I ../../ ../../extensions/browser/api/declarative_net_request/flat/extension_ruleset.fbs
[fail1.txt](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/files/6412245/fail1.txt)

[  647s] flatc failed with exit code -5

```

**Comment by jstkdng** [comment]
that array is used to keep libraries that shouldn't be deleted, not to use the system counterparts

**Comment by Area51Kacz** [comment]
Failed.. my next attempt (adding chromium-dev             'rtc_use_pipewire=true' +      'rtc_pipewire_version="0.3"'   flags)

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chromium-dev

**Comment by Area51Kacz** [comment]
as an extra point... chromium-dev **aint** has chromium-90 ... they jumped straight to 91

**Comment by jstkdng** [comment]
Just managed to get it to build but the resulting package is unstable af.

**Comment by Area51Kacz** [comment]
@jstkdng as crashing

or having bugs  (failing at sites)

**Comment by jstkdng** [comment]
@Area51Kacz 
it segfaults while loading any site, had to downgrade.
>and... could we try to add this flatbuffers at this (declare -gA _system_libs) array?
nope, that is for only a few libraries, not third party binaries

**Comment by Area51Kacz** [comment]
And 

1 could u post these segfaults (to guess what its crashing) xd

2 could these gn flags  mitigate it 
    'rtc_use_pipewire=true'
    'rtc_pipewire_version="0.3"'

_are loved by both arch chromium and   aur chromium-dev_
https://github.com/archlinux/svntogit-packages/blob/master/chromium/trunk/PKGBUILD
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chromium-dev

**Comment by jstkdng** [comment]
@Area51Kacz

1. not really, I'm building release builds on the OBS, can't get debug info from that, just sigsegv when trying to load a page
2. already have those flags in my PKGBUILD, they don't fix this problem.

**Comment by Area51Kacz** [comment]
And..  inviting pipewire?

On chromium-dev https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chromium-dev
         ```

if [ "${_use_wayland}" = "1" ]; then
  depends+=('pipewire')
fi
```

on gentoo-chromium https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/chromium/chromium-90.0.4430.93.ebuild

```
		wayland? (
			screencast? ( media-video/pipewire:0/0.3 )
		)
```

**Comment by jstkdng** [comment]
I have it on opt depends, check it out: https://github.com/jstkdng/aur/blob/master/ungoogled-chromium/PKGBUILD
```
optdepends=('pipewire: WebRTC desktop sharing under Wayland'
            'kdialog: needed for file dialogs in KDE'
            'org.freedesktop.secrets: password storage backend on GNOME / Xfce'
            'kwallet: for storing passwords in KWallet on KDE desktops')
```

**Comment by Area51Kacz** [comment]
[df.txt](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/files/6412434/df.txt)

**Comment by Area51Kacz** [comment]
@jstkdng but... try to make pipewire mandatory  (at depends)

**Comment by jstkdng** [comment]
@Area51Kacz no

**Comment by Area51Kacz** [comment]
And

1  could we be .. cursed to migrate to bromite system? https://github.com/nikolowry/bromite-builder/  

2 does segfaulting calms down  if we run --no-sandbox flag? (on the binary)

_Brave USED to made throw a similar drama  - and they disabled this flag on the binary_
https://www.reddit.com/r/brave_browser/comments/bieupq/brave_has_sandbox_disabled_on_arch_linux_is_this/

**Comment by networkException** [comment]
@Area51Kacz This has nothing to do with bromite and --no-sandbox is not an option to use in a privacy and security focused project like ungoogled-chromium. Please refrain from commenting unrelated things

**Comment by Area51Kacz** [comment]
@networkException But..   does this _calms_ the issue or not   (as morbid curiosity) 
_and cz its sometimes used with firejail (firejail brave)_

**Comment by networkException** [comment]
I will not argue with you why it's an extremely bad idea to disable sandboxing in a modern browser. Again, please stop sending unrelated and useless comments

**Comment by braewoods** [comment]
@Area51Kacz @networkException is correct. You're wasting our time. If you persist I will be forced to take action to correct it.

**Comment by Area51Kacz** [comment]
And;;; as the last crazy question

Its obs  ...  failing at (classic) chromium too  _(to know if its a build-flag ... or a deep-native problem)_

**Comment by jstkdng** [comment]
did you ban them @braewoods ?

**Comment by braewoods** [comment]
No, I don't have that ability. I only deleted the comments.

**Comment by jstkdng** [comment]
Alright, finally managed to get a working build of uc

![image](https://user-images.githubusercontent.com/52050345/116839805-41f73c80-ab99-11eb-8f8b-cb06a7e26381.png)

The fix was setting CFLAGS to previous values known to work
```
  # use fixed flags as system flags break build
  CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt"
  CXXFLAGS="$CFLAGS"

  # Facilitate deterministic builds (taken from build/config/compiler/BUILD.gn)
  CFLAGS+='   -Wno-builtin-macro-redefined'
  CXXFLAGS+=' -Wno-builtin-macro-redefined'
  CPPFLAGS+=' -D__DATE__=  -D__TIME__=  -D__TIMESTAMP__='
```

**Comment by jstkdng** [comment]
Maybe the arch devs will find a better solution in future releases, if they do we can update our own.

**Comment by bsdice** [comment]
I also succeeded with a build of 90.0.4430.93, after over 6+ hours compilation, using

> CPPFLAGS="-D_FORTIFY_SOURCE=2"
> CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt"
> CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt"
> LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
> MAKEFLAGS="-j$(($(nproc)+1))"
> DEBUG_CFLAGS="-g -fvar-tracking-assignments"
> DEBUG_CXXFLAGS="-g -fvar-tracking-assignments"

Quick check using VcXsrv X11 over network showed no crashes while browsing various sites.

So miscompile bug is upstream in clang, judging from PKGBUILD makedepends?

**Comment by braewoods** [comment]
It's either that or they foolishly enabled a risky optimization globally. Not all optimizations are intended to be used in all cases.

**Comment by bsdice** [comment]
Or, they only tested the new flags thoroughly with gcc and not clang. For example https://github.com/archlinux/svntogit-community/blob/packages/flatbuffers/trunk/PKGBUILD depends on gcc-libs, so gcc.

In either case why is https://github.com/archlinux/svntogit-packages/commits/packages/chromium/trunk not showing the build defect? Pacman not yet updated on pkgbuild.com, or using older makepkg.conf overriding new one, or something else, would be interesting to know.

**Comment by Area51Kacz** [comment]
Im trying both experiments xd

@jstkdng https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/ungoogled-chromium-arch

@bsdice https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/ungoogled-chromium-arch222

**Comment by nikolowry** [comment]
@Ahrotahn great catch! Makes total sense why the maintainers of `chromium` could push new builds while mine would fail locally.

@jstkdng I was able to build successfully with the latest AUR push!

Prior to that, I was also able to build successfully with the `makepkg.conf` changes by removing `-fcf-protection` and `-fexceptions`:
```bash
CFLAGS=${CFLAGS/-fexceptions}
CFLAGS=${CFLAGS/-fcf-protection}
CXXFLAGS="$CFLAGS"

# Facilitate deterministic builds (taken from build/config/compiler/BUILD.gn)
CFLAGS+='   -Wno-builtin-macro-redefined'
CXXFLAGS+=' -Wno-builtin-macro-redefined'
CPPFLAGS+=' -D__DATE__=  -D__TIME__=  -D__TIMESTAMP__='
```
But that resulted in a crash during page load like @jstkdng previously described. So it does seem the best route to take is hard setting the `CFLAGS`. I'm not a C/C++ developer, so I won't speculate on what the most optimal `CFLAGS` might be.

Regardless, great job everyone for working through this!

**Comment by Area51Kacz** [comment]
@bsdice its working  (tried some news sites + youtube + radiostreaming ...  id try if discord works too)

**Comment by skrat** [comment]
So is this going to be available at some point? Right now the repo is empty. 

https://download.opensuse.org/repositories/home:/ungoogled_chromium/Arch/x86_64

**Comment by jstkdng** [comment]
@skrat 

It's available on my repository and in the aur

**Comment by braewoods** [comment]
Well it's basically this way because of the dumpster fire that came about due to changes in Arch. I have yet to fix the build.

**Comment by networkException** [comment]
> Alright, finally managed to get a working build of uc
> 
> ![image](https://user-images.githubusercontent.com/52050345/116839805-41f73c80-ab99-11eb-8f8b-cb06a7e26381.png)
> 
> The fix was setting CFLAGS to previous values known to work
> 
> ```
>   # use fixed flags as system flags break build
>   CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt"
>   CXXFLAGS="$CFLAGS"
> 
>   # Facilitate deterministic builds (taken from build/config/compiler/BUILD.gn)
>   CFLAGS+='   -Wno-builtin-macro-redefined'
>   CXXFLAGS+=' -Wno-builtin-macro-redefined'
>   CPPFLAGS+=' -D__DATE__=  -D__TIME__=  -D__TIMESTAMP__='
> ```

I mean those flags work fine, why not use them until there's an upstream fix?

**Comment by Area51Kacz** [comment]
@networkException and these flags works on bare obs _(clean instalation)_

**Comment by networkException** [comment]
@braewoods I'm not really a C++ dev myself or anything, is there anything stopping us from using said build flags? There don't seem to be any runtime issues at all

**Comment by braewoods** [comment]
@networkException Go ahead then. I'm not an Arch user myself so it really doesn't matter to me what you do as long as it builds.

**Comment by Area51Kacz** [comment]
and @networkException these flags leads to faster builds _(its good regardless if we build on pc - 
**laptop**  or the cloud _

**Comment by networkException** [comment]
Can you stop commenting on closed issues about things that do not contribute to this project in any helpful way?

**Comment by skrat** [comment]
@networkException well allow me to break the rules on necrobumping, but there is still no package in the OBS repo that you advertise in the README

**Comment by networkException** [comment]
Huh are you sure? I have the repository in my pacman conf (cat output of that above) and pacman can definitely find the package... I will quickly test installing in a docker container as I already installed the package manually from a workflow artifact
![image](https://user-images.githubusercontent.com/42888162/118372440-e9209e80-b5b1-11eb-82ff-5b3c3dda35ce.png)

**Comment by DAC324** [comment]
> > The error I see is this: `flatc failed with exit code -5`
> > And the AUR users also have the same issue. So it seems to be an issue for more than just us. See here in the comments:
> > https://aur.archlinux.org/packages/ungoogled-chromium
> 
> Additional context to hopefully helps with investigating:
> 
> * Same error when using the latest version of `third_party/llvm-build` (emulated how `chromium-dev` does  it: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chromium-dev#n467)
> * I can successfully build the latest Bromite release, v90.0.4430.92 with my `bromite-builder` utility script (https://github.com/nikolowry/bromite-builder/). It uses `gclient` and the toolchain provided by Chromium.

The same applies to `protoc` and `protozero_plugin`. If compiled with the system `clang 11`, both fail with an exception (signal 5). 
You _must_ use the `clang` version downloadable via the `tools/update.py` script.
