### ISSUE TITLE
Segmentation fault when launching browser

### ISSUE THREAD

**Issue by paniash** [ungoogled-software/ungoogled-chromium-archlinux#124]
On running the binary from the OBS repository (installed using the instructions in the README). However, the browser launches and after about 15 seconds, crashes and yields a segmentation fault. I get the following error log:

```sh
[20271:20305:0501/134832.661786:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse ser
[20271:20305:0501/134832.661854:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse ser
[20271:20305:0501/134832.673235:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse ser
[20271:20305:0501/134832.673407:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse ser
[20301:20301:0501/134832.744800:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
zsh: segmentation fault  chromium
```

I'd be glad if you could help.

**Comment by networkException** [comment]
Hello, would it be possible that you tried installing the package artifact from the latest github actions run? It would be this one https://github.com/ungoogled-software/ungoogled-chromium-archlinux/runs/2451976271, the latest commit on master didn't finish the pipeline properly

**Comment by paniash** [comment]
No. I simply added the OBS repository into `/etc/pacman.conf` as per the instructions in the README and installed the package using 
```
sudo pacman -Sy ungoogled-chromium
```

**Comment by networkException** [comment]
oh sorry I misworded my comment, I meant to say "would it be possible that you try to install"

**Comment by paniash** [comment]
@networkException Aha, I see. Before I do that, I'd like to mention an update on the matter. I wanted to install some addons and went the non-purist way and installed them on chromium and later uninstalled it and installed ungoogled-chromium once again. Strangely enough, it works fine now and doesn't crash with a segmentation fault.

**Comment by networkException** [comment]
oh alright, well good to hear. I'd just close the issue and if the error reoccurs it can be reopened

**Comment by paniash** [comment]
Cool. Thanks.
