### ISSUE TITLE
Issue installing from OBS repository

### ISSUE THREAD

**Issue by blipk** [ungoogled-software/ungoogled-chromium-archlinux#125]
Previously I had installed from the OBS repository after adding it to /etc/pacman.conf, however after an OS reinstall it no longer seems to be able to find the package:

```
sudo pacman -Sy ungoogled-chromium                                                                                                                                                              
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 home_ungoogled_chromium_Arch is up to date
error: target not found: ungoogled-chromium
```

Any help or indication what the issue might be would be appreciated, I had followed the instructions in the README here to the letter.

**Comment by networkException** [comment]
The release OBS repository is currently not populated due to #123, you could use the testing one instead for now
```
[home_ungoogled_chromium_testing_Arch]
SigLevel = Required TrustAll
Server = https://download.opensuse.org/repositories/home:/ungoogled_chromium:/testing/Arch/$arch
```

**Comment by blipk** [comment]
Thanks for the update @networkException 
I will stick with the AppImage until the builds are working.

**Comment by networkException** [comment]
The release OBS repository now should have the latest version
