### ISSUE TITLE
Update to Chromium 90.0.4430.212

### ISSUE THREAD

**Issue by Area51Kacz** [ungoogled-software/ungoogled-chromium-archlinux#126]
Could we update to 90.0.4430.212? 

Based on https://omahaproxy.appspot.com/ updates >)

**Comment by Area51Kacz** [comment]
And could we publish it as _(contribution)_ package
https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/ungoogled-chromium-arch
https://build.opensuse.org/package/binaries/home:Area51Kacz:branches:home:ungoogled_chromium:testing/ungoogled-chromium-arch/Arch

**Comment by networkException** [comment]
I prefer to use the binaries from github actions or out own obs package.
