### ISSUE TITLE
arch repository does not work

### ISSUE THREAD

**Issue by githlp** [ungoogled-software/ungoogled-chromium-archlinux#127]
sudo pacman -Sy ungoogled-chromium
...
home_ungoogled_chromium_Arch is up-to-date
error: target not found: ungoogled-chromium

**Comment by networkException** [comment]
Sorry for the inconvenience, please see https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/125 for more information

**Comment by networkException** [comment]
The release OBS repository now should have the latest version
