### ISSUE TITLE
CI: Improved container support is not enabled for the organization

### ISSUE THREAD

**Issue by networkException** [ungoogled-software/ungoogled-chromium-archlinux#132]
All ci workflows with a non pull request trigger event currently fail due to them not being able to push images to `ghcr.io`. This feature is currently still in beta and requires an organization global flag to be set.

@Eloston do you think you could enable this? I haven't noticed any issues while testing on my fork but I would also understand if you wouldn't want to enable a beta feature.

How to enable support can be found [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/enabling-improved-container-support-with-the-container-registry#enabling-the-container-registry-for-your-organization-account)

**Comment by Eloston** [comment]
OK, I've enabled the feature with Container Creation set to Private only (the default). Let me know if this should be changed.

**Comment by networkException** [comment]
I'm a bit confused about the visibility system github uses, as I'm able to see and pull the two new packages without any authentication but that was an initial goal with the move anyways.

Could you also remove the outdated [docker.pkg.github.com/ungoogled-chromium-archlinux](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/packages/766996) package?

**Comment by Eloston** [comment]
Both ungoogled-chromium-archlinux and ungoogled-chromium-archlinux-testing already seem to be set as public. I've deleted the outdated package.
