### ISSUE TITLE
Disable debug symbols to improve compile speeds

### ISSUE THREAD

**Issue by Area51Kacz** [ungoogled-software/ungoogled-chromium-archlinux#133]
I write one issue for both topics

1  we should prepare for chromium 91  _(when unggogle updates to 91)_

2 we could add  a weightloss flag _(as symbol-level 0)_

`'blink_symbol_level=0'`
`'is_debug=false'
``'symbol_level=0'`

**Comment by networkException** [comment]
I have already prepared the patch changes from https://github.com/archlinux/svntogit-packages/commit/7cd2f08852ca3b88237a5c563eb8cfc5e471e489 on my local machine, when a new upstream release gets published I will try to push those as fast as possible.

About the flag change I am personally unsure. On the one hand I can't think of any negative side effects from applying the change, but on the other hand there doesn't not seem to be an obvious reason to reduce the ~90MB package size, thats reasonable.

Additionally I believe that the user experience of this package should not be too different from the one the official `chromium` package provides, some users might be interested in more detailed backtraces. I like to think of this package as a drop in replacement for `chromium`, with only the changes that all other `ungoogled-chromium` packages share as well.

**Comment by Area51Kacz** [comment]
Sorry  _(my misunderstanding)_

When i say weighloss  its about buildtime  _(faster builds)_

**Comment by networkException** [comment]
I will test the speed difference once 91 is out

**Comment by networkException** [comment]
I can't confirm any speed improvement when enabling the flags you mentioned.
