### ISSUE TITLE
libstdc++.so.6 issue after upgrading to 91

### ISSUE THREAD

**Issue by DudmasterUltra** [ungoogled-software/ungoogled-chromium-archlinux#134]
Hi,

I use the Open Build Service Repository to install ungoogled-chromium. It has worked until the recent upgrade to 91. When launching in the terminal, the following two errors are displayed:

`
/usr/lib/chromium/chromium: /usr/lib/libstdc++.so.6: version 'GLIBCXX_3.4.29' not found (required by /usr/lib/chromium/chromium)
`
`
/usr/lib/chromium/chromium: /usr/lib/libstdc++.so.6: version 'CXXABI_1.3.13' not found (required by /usr/lib/chromium/chromium)
`

After researching online, I've found that my libstdc++.so.6 doesn't contain those specific versions, but older and newer ones. I also did a downgrade of ungoogled-chromium to temporarily fix it, which is working for now. How do I go about fixing this, or is it an issue with the build? I don't have anything non-standard about my installation of these libraries. OS is Manjaro.

Thanks.

**Comment by jstkdng** [comment]
It's an issue with manjaro as they test packages before pushing updates. You have 3 options:
a) downgrade until manjaro updates their packages
b) compile uc on your pc
c) stop using manjaro and use arch
Unfortunately, we can't do anything else to help you m8
