### ISSUE TITLE
Prepare for chromium 92.0.4515.131

### ISSUE THREAD

**Issue by Area51Kacz** [ungoogled-software/ungoogled-chromium-archlinux#138]
Could we prepare for chromium 92.0.4515.107

https://github.com/archlinux/svntogit-packages/commit/78c86ecddcd707d7c90c4c03b26d736e0e9610fb
https://github.com/archlinux/svntogit-packages/commit/042a79d94343afffbc9bccfde2bda6f8735401d5

https://github.com/Eloston/ungoogled-chromium/pull/1573

**Comment by networkException** [comment]
I already took care of that locally, as soon as Eloston/ungoogled-chromium gets a new release I will push the commits and the tag
