### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by HeyBoy85** [ungoogled-software/ungoogled-chromium-archlinux#14]
The build process crash at "CXX obj/components/viz/service/service/service_jumbo_1.o"

build log: https://pastebin.com/HsTUwazC
/tmp/service_jumbo_1-b74385.cpp: https://nofile.io/f/OG5HEPuuBfM
/tmp/service_jumbo_1-b74385.sh: https://pastebin.com/P8De5TjS

**Comment by tangalbert919** [comment]
It looks like the process "clang" was killed during the build, possibly from running out of RAM. Try building again.

**Comment by Eloston** [comment]
I agree with @tangalbert919. One solution is to add swap space.

**Comment by HeyBoy85** [comment]
I tried two more times and the crash happened every time. My machine has 16GB of ram available and during the build process it never happened to use more then 5GB. Maybe I use a wrong version (maybe bugged?) of clang (I have installed clang 8.0.0-4)? If there are other logs I can provide I'd be happy to help

**Comment by Eloston** [comment]
Hmm, strange. I'll reopen.

Considering an external signal killed the process, it's likely that the system is killing it for some reason. You could check your system logs (kernel, dmesg, etc.) to see if there are any messages of interest around the time the compiler is killed.

However, LLVM 8.0.1 is stable; there is a possibility upgrading could help.

**Comment by JostBrand** [comment]
Ist flooding my tmpfs doesnt matter which size i set 40 GB wasnt enough and then build fails bc it can write

**Comment by nikolowry** [comment]
Not able to replicate with the latest commit, https://github.com/ungoogled-software/ungoogled-chromium-archlinux/commit/c0b3356176224af62ccb0b954114ffa83febe5fd.

The build took a total of 1 hour and 10 mins on my machine, `neofetch` details on that machine are as followed:
```
OS: Arch Linux x86_64 
Host: Precision 5530 
Kernel: 5.1.4-arch1-1-ARCH 
Uptime: 2 hours, 5 mins 
Packages: 932 (pacman) 
Shell: zsh 5.7.1 
DE: GNOME 3.32.2 
Theme: Adwaita [GTK2/3] 
Icons: Paper [GTK2/3] 
Terminal: tilix 
CPU: Intel i9-8950HK (12) @ 4.800GHz 
GPU: NVIDIA Quadro P2000 Mobile 
GPU: Intel UHD Graphics 630 
Memory: 4379MiB / 31875MiB 
```

None of these suggestions at https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md#Tips_tricks_and-troubleshooting helps?

**Comment by tangalbert919** [comment]
I have not been able to replicate this error, but when I do get to "jumbo", my computer freezes instead. Sadly, that freeze doesn't go away, even after several minutes.

**Comment by HeyBoy85** [comment]
Sorry, but i had no time in these days.
Anyway, I tried to increase tmpfs size (up to 25GB) and also a a swap file (40GB), but the everytime I tried to build (by tryzen, that use tmpfs, or directly using makepkg in a folder inside my ssd) it ends with a system freeze (it eats all the ram (16GB) and the system seems to not swap quickly enough (but I have set vm.swappiness to 100)).
PS: I have not used these flags (`is_debug = false` and `symbol_level = 0`) because they are already in [here](https://github.com/Eloston/ungoogled-chromium/blob/master/flags.gn)
PSS: all these test are made with the last PKGBUILD (74.0.3729.169-1)

**Comment by Eloston** [comment]
I just noticed that there is no flag setting for `jumbo_file_merge_limit` in our GN config. I've had issues with the default value for this flag causing my system to OOM in the past, so perhaps you should set it to a lower number. I have found the value of `8` to be safe for my Debian builds (i.e. `jumbo_file_merge_limit=8`).

**Comment by dimyme** [comment]
I had the same problem.

SOLVED!   https://aur.archlinux.org/packages/ungoogled-chromium#comment-697850
