### ISSUE TITLE
Well, chaotic-aur is a third party repository, you should ask them to update, not us.

### ISSUE THREAD

**Issue by kayal28** [ungoogled-software/ungoogled-chromium-archlinux#140]
Well, chaotic-aur is a third party repository, you should ask them to update, not us.

_Originally posted by @jstkdng in https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/81#issuecomment-627328203_

**Comment by networkException** [comment]
Why did you open this issue?

**Comment by kayal28** [comment]
> فتحت

**Comment by networkException** [comment]
Please only open an issue if there's an actual reason
