### ISSUE TITLE
Publish binary release to AUR

### ISSUE THREAD

**Issue by victormihalache** [ungoogled-software/ungoogled-chromium-archlinux#143]
Lots of packages have a source and a binary AUR package, how come this project doesn't?

**Comment by SafwanLjd** [comment]
Any updates on this?

**Comment by networkException** [comment]
Eloston told me personally that he's quite busy but will look into the internal issue that is blocking this as soon as possible

**Comment by pc00per** [comment]
> Eloston told me that he's quite busy but will look into the internal issue that is blocking this as soon as possible

Tq mate. I hope this gets into the AUR do that we can enjoy ungoogled-chromium without wasting our time on compilations.

**Comment by jstkdng** [comment]
I still can't wrap my head around the fact that a lot of ppl don't want to edit their pacman config and add a repo for this project. Ubuntu and debian folks will gladly add a ppa but arch folks won't. Is it just that they don't know about the existence of all binary repositories? Is the pinned comment on the aur not enough?

**Comment by jstkdng** [comment]
@SafwanLjd is the OBS repository created from this github repo not official enough? Don't let the perfect be the enemy of the good bruh

**Comment by pc00per** [comment]
`ungoogled-chromium-xdg-bin` seems to work fine

**Comment by jstkdng** [comment]
@pc00per 

I'd say that is because the guy that had the personal vendetta against ungoogled-chromium-bin (for some reason) doesn't seem to care/disappeared.

**Comment by networkException** [comment]
Someone poked the arch people so I was able to submit the package :tada: 

I will close this issue, lets hope my CI works properly when tagging the next release :sweat_smile:

**Comment by pc00per** [comment]
I wish poking people shouldn't be necessary in the future for packages to submit 😅
