### ISSUE TITLE
 Getting error after running ungoogled-chromium in Manjaro

### ISSUE THREAD

**Issue by miguelcarcamov** [ungoogled-software/ungoogled-chromium-archlinux#145]
Hello, when I run chromium and then I start to using it (like opening a tab or any action) I get this message from the terminal:
```

[1506272:1506286:0914/131954.381276:ERROR:ev_root_ca_metadata.cc(841)] Failed to register OID: 0
Segmentation fault (core dumped)
```

I have tried both installing from the AUR and installing the binary and in both cases I get the same result.

**Comment by networkException** [comment]
I can't reproduce this on a clean install in a vm

**Comment by miguelcarcamov** [comment]
I figure out that since I had chromium installed before I had to delete .cache/chromium and .config/chromium

**Comment by caniko** [comment]
@miguelcarcamov thanks!
