### ISSUE TITLE
OBS builds stuck again?

### ISSUE THREAD

**Issue by skrat** [ungoogled-software/ungoogled-chromium-archlinux#146]
$subj

**Comment by networkException** [comment]
Could you elaborate further please? What exactly do you mean by stuck?

**Comment by skrat** [comment]
```
~ $ sudo pacman -Syy
Place your finger on the fingerprint reader
:: Synchronizing package databases...
 core                                      138.5 KiB   280 KiB/s 00:00 [########################################] 100%
 extra                                    1585.4 KiB  1287 KiB/s 00:01 [########################################] 100%
 community                                   5.8 MiB  2.92 MiB/s 00:02 [########################################] 100%
 home_ungoogled_chromium_Arch             1309.0   B  2.18 KiB/s 00:01 [########################################] 100%
~ $ sudo pacman -Ss | grep chromium
extra/chromium 93.0.4577.82-1
community/browserpass-chromium 3.7.2-1 [installed]
community/chromium-bsu 0.9.16.1-1
    Headless chrome/chromium automation library
home_ungoogled_chromium_Arch/ungoogled-chromium 92.0.4515.159-1 [installed]
~ $ grep -A3 chromium /etc/pacman.conf 
[home_ungoogled_chromium_Arch]
SigLevel = Required TrustAll
Server = https://download.opensuse.org/repositories/home:/ungoogled_chromium/Arch/$arch
~ $ 
```

So chromium is at `93.0.4577.82-1` while ungoogled-chromium is stuck at `92.0.4515.159-1` for quite a while (29 days). The current version has weird bug where it displays artifacts over images, I'm eagerly waiting for the 93+ update. Thank you

**Comment by skrat** [comment]
Please excuse, I might not be well enough educated about OBS, I see you made 80f1f75150671203ada5f49c96b5fb2855709775 but I don't see anything happening in OBS. Do you need to submit a request manually?

**Comment by networkException** [comment]
OBS and GitHub releases are tied to tags in the git history.

The ungoogled-chromium repository only has a pull request with support for 93 versions at the moment so I can't create a new git tag here

**Comment by networkException** [comment]
I have on commit builds in the testing OBS repository on my todo list but that will take a while still. Until now I recommend that you download the package artifact from the latest successful GitHub Actions run, those also run on commit

**Comment by networkException** [comment]
The OBS repository now contains the latest chromium release.

**Comment by skrat** [comment]
@networkException thanks, I appreciate the work you're doing
