### ISSUE TITLE
Ungoogled Chromium fails to start on latest build

### ISSUE THREAD

**Issue by FivePixels** [ungoogled-software/ungoogled-chromium-archlinux#151]
Each time I try to run `chromium --enable-features=UseOzonePlatform --ozone-platform=wayland`, Chromium fails to start with the following output:

```
[11325:11325:0923/092751.744935:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is egl
[11325:11325:0923/092751.762090:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[11290:11290:0923/092751.786607:ERROR:cursor_loader.cc(115)] Failed to load a platform cursor of type kNull
[11290:11290:0923/092751.896508:ERROR:platform_shared_memory_region_posix.cc(47)] Descriptor access mode (0) differs from expected (2)
fish: Job 1, 'chromium --enable-features=UseO…' terminated by signal SIGTRAP (Trace or breakpoint trap)
```
`chromium --version`
```
Chromium 93.0.4577.82 Arch Linux
```

I'm not sure if this is an issue specific to this software or something with my configuration. I tried installing the default chromium package and it is having the same issue. The same sort of error is happening in the Brave browser [here](https://github.com/brave/brave-browser/issues/17689).

**Comment by networkException** [comment]
Does this issue persist when using chromium 94? You can download a build from here: https://github.com/ungoogled-software/ungoogled-chromium-archlinux/suites/3842943752/artifacts/95591713

**Comment by FivePixels** [comment]
> Does this issue persist when using chromium 94? You can download a build from here: https://github.com/ungoogled-software/ungoogled-chromium-archlinux/suites/3842943752/artifacts/95591713

Appears to have a similar output:
```
[37809:37809:0923/095225.786871:ERROR:cursor_loader.cc(115)] Failed to load a platform cursor of type kNull
[37849:37849:0923/095225.823481:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is egl, ANGLE is 
[37849:37849:0923/095225.847798:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[37809:37809:0923/095225.975383:ERROR:platform_shared_memory_region_posix.cc(47)] Descriptor access mode (0) differs from expected (2)
fish: Job 1, 'chromium --enable-features=UseO…' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by networkException** [comment]
It's probably better to report this in the arch issue tracker or chromium issue tracker. I can't reproduce this is a manjaro vm with wayland so its probably some issue that is more hardware related (maybe the gpu driver)

**Comment by FivePixels** [comment]
> It's probably better to report this in the arch issue tracker or chromium issue tracker. I can't reproduce this is a manjaro vm with wayland so its probably some issue that is more hardware related (maybe the gpu driver)

Makes sense. I was having the `undefined symbol: hb_subset_input_set_retain_gids` issue on my desktop until I installed 94. I'm having this issue on my Macbook where I've got Arch installed, so I'd also assume it's something to do with my GPU drivers. I'll take a look - thanks for the direction.

**Comment by networkException** [comment]
The undefined symbol error is #147

**Comment by ptr1337** [comment]
I also built it in a chroot. Running without problems. Even built with -march=x86-64-v3.

**Comment by danfos** [comment]
Did Arch maybe switch to glibc 2.34? On OpenSuse Tumbleweed I see after the glibc 2.34 update that the executable that was working before is not longer working, it is crashing. Running with --no-sandbox works.

**Comment by networkException** [comment]
No, arch is on glibc 2.33

**Comment by FivePixels** [comment]
Found my issue, completely unrelated to ungoogled-chromium. I don't know why it works now but it does. I re-enabled an ACPI interrupt that was happening at gpe6D on my system. I originally thought that this ACPI interrupt was an issue but I'm not sure (it had a bunch of interrupts happening). I also purged my `chromium-flags.conf` and my `~/.config/chromium` folder. After rebooting, even after enabling gpe6D it is still disabled, but chromium opens, so it's a win in my book. The ACPI interrupt might be completely irrelevant. Anyone else having this happen should purge the file and folder I previously mentioned first and try rebooting. *Deleting `~/.config/chromium` will remove bookmarks and saved data in your browser.

**Comment by FivePixels** [comment]
Update again: seems to be the `chromium-flags.conf` file causing it alone. According to the [Arch Wiki](https://wiki.archlinux.org/title/HiDPI), this seems to be the only way to force a scale factor on the browser with a HiDPI display. Not sure how to get HiDPI in my browser now, at least it works though.
