### ISSUE TITLE
Dependencies not automatically installed

### ISSUE THREAD

**Issue by knuxyl** [ungoogled-software/ungoogled-chromium-archlinux#152]
I am trying to build latest on Arch system. Makepkg is not automatically retrieving dependencies like the readme says. It does list missing packages, but I cannot even find some of them, like ttf-liberation.

> ==> Making package: ungoogled-chromium 94.0.4606.61-1 (Tue 28 Sep 2021 07:13:57 PM CDT)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> ttf-liberation
  -> libva
  -> snappy
  -> ffmpeg
  -> minizip
  -> re2
==> Checking buildtime dependencies...
==> Missing dependencies:
  -> gn
  -> ninja
  -> clang
  -> lld
  -> gperf
  -> nodejs
  -> pipewire
  -> java-runtime-headless
==> ERROR: Could not resolve all dependencies.

**Comment by networkException** [comment]
For now you could try installing the packages listed in https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/master/.github/workflows/container/Dockerfile on line 18 as well. If that isn't enough either installing make dependencies and normal dependencies manually should work.

**Comment by networkException** [comment]
I've done a bit of testing and it seems like this is caused by the user you are building with not having access to sudo (which is used by makepkg internally)

**Comment by jstkdng** [comment]
Try running `makepkg -sr`, the `s` option should install all dependencies
