### ISSUE TITLE
Chromium refuses to start due to ICU (Manjaro)

### ISSUE THREAD

**Issue by psychedelic-fox** [ungoogled-software/ungoogled-chromium-archlinux#157]
Upon running `chromium` (96.0.4664.45-2) in terminal, I am met with this error:

`/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.70: cannot open shared object file: No such file or directory`

Is there any way to downgrade this package to a usable state until ICU 70 is available?

**Comment by networkException** [comment]
You can run `pacman -U https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/download/96.0.4664.45-1/ungoogled-chromium-96.0.4664.45-1-x86_64.pkg.tar.zst` to get the previous release which is linked against icu 69 until Manjaro updates their icu zu 70 as well.

**Comment by psychedelic-fox** [comment]
> You can run `pacman -U https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/download/96.0.4664.45-1/ungoogled-chromium-96.0.4664.45-1-x86_64.pkg.tar.zst` to get the previous release which is linked against icu 69 until Manjaro updates their icu zu 70 as well.

`:: Retrieving packages...
 ungoogled-chromi...    99.5 MiB  16.1 MiB/s 00:06 [---------------------] 100%
error: failed retrieving file 'ungoogled-chromium-96.0.4664.45-1-x86_64.pkg.tar.zst.sig' from github.com : The requested URL returned error: 404
warning: failed to retrieve some files`

**Comment by networkException** [comment]
Ah pacman doesn't like that, try
```
wget https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/download/96.0.4664.45-1/ungoogled-chromium-96.0.4664.45-1-x86_64.pkg.tar.zst
pacman -U ungoogled-chromium-96.0.4664.45-1-x86_64.pkg.tar.zst
```

**Comment by psychedelic-fox** [comment]
that works! thank you
