### ISSUE TITLE
Ungoogled Chromium failing to launch

### ISSUE THREAD

**Issue by LeonardoMantovani** [ungoogled-software/ungoogled-chromium-archlinux#158]
I installed ungoogled chromium using these prebuilt binaries and everything worked correctly untill few days ago when it started to give me this error when I launch it:
`usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.70: cannot open shared object file: No such file or directory`

I think this may be because it needs a rebuild (check [here](https://bbs.archlinux.org/viewtopic.php?id=271564))
Can you please fix this? :)

**Comment by ptr1337** [comment]
You need to update to the latest icu version (70.1)

**Comment by networkException** [comment]
If you are on arch you need to update your system, if you are on distro without up to date repositories see #157
