### ISSUE TITLE
error while loading shared libraries: libicui18n.so.70: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by br4nnigan** [ungoogled-software/ungoogled-chromium-archlinux#159]
Won't start anymore, reinstalling didn't help.

![image](https://user-images.githubusercontent.com/10244835/145581605-b0423f3a-1f45-442b-afe0-8cd38ea0be3a.png)

**Comment by networkException** [comment]
icu 70.1-1 has been released over 3 weeks ago, please make sure your system is up to date.

**Comment by br4nnigan** [comment]
Thanks for the comment, I did that before creating the ticket:

        $ sudo pacman -Syu 
        :: Synchronizing package databases...
         core is up to date
         extra is up to date
         community is up to date
         multilib is up to date
         sublime-text is up to date
         home_ungoogled_chromium_Arch is up to date
        :: Starting full system upgrade...
        warning: manjaro-hello: local (0.6.7-2) is newer than extra (0.6.6-9)
         there is nothing to do

**Comment by networkException** [comment]
Ah manjaro, well as they didn't update icu yet you can either install the up to date version manually (from testing for example) or downgrade ungoogled-chromium to `96.0.4664.45-1`
