### ISSUE TITLE
ungoogled-chromium-96.0.4664.110-1-x86_64 Fails to start

### ISSUE THREAD

**Issue by avbobylev** [ungoogled-software/ungoogled-chromium-archlinux#160]
Was sent here from ```chaotic-aur``` repo.

* What happens?

Package ```ungoogled-chromium-96.0.4664.110-1-x86_64``` fails to start with an error:

```bash
/usr/lib/chromium/chromium: symbol lookup error: /usr/lib/chromium/chromium: undefined symbol: wl_proxy_marshal_flags
```

Previous version of the package ```ungoogled-chromium-96.0.4664.93-1-x86_64``` runs as expected.

I have ```wailand-protocols``` installed

```bash
local/wayland-protocols 1.24-1
    Specifications of extended Wayland protocols
```

But I use regular x11 session

* What is expected to happen?

Package starts without an error.

ps I use Manjaro, btw.

**Comment by networkException** [comment]
`96.0.4664.110-1` got linked against `extra/wayland 1.20.0-1`, manjaro is still on `1.19.0-2`
