### ISSUE TITLE
VAAPI wayland support patch

### ISSUE THREAD

**Issue by mizzunet** [ungoogled-software/ungoogled-chromium-archlinux#161]
Would you please add [this patch](https://aur.archlinux.org/cgit/aur.git/tree/0001-ozone-wayland-add-VA-API-support.patch?h=chromium-wayland-vaapi) for VAAPI support for Wayland, from `chromium-wayland-vaapi`?

Thanks

**Comment by networkException** [comment]
I usually try to stay as close to extra/chromium as possible, maybe it would be better to have the patch be part of the arch or chromium upstream?

**Comment by mizzunet** [comment]
I'd request it there then.

I doubt if there would accept it, as that's might be why `chromium-wayland-vaapi` came

**Comment by gothmog123** [comment]
Pretty please.... We would appreciate it so much

**Comment by networkException** [comment]
How is the patch licensed?

**Comment by gothmog123** [comment]
this is where the patch comes from: https://github.com/OSSystems/meta-browser

**Comment by networkException** [comment]
Alright, I will look into adding the patch for the next release. It seems like chromium upstream will also include fixes for wayland in the future, according to the description of the patch

**Comment by gothmog123** [comment]
Thank you

**Comment by networkException** [comment]
As mentioned in the commit, 101.0.4951.41-1 does not include the patch as it hasn't updated yet and causes conflicts. I will create a new release as soon as possible

**Comment by networkException** [comment]
I messed up the pull request mentions in https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/tag/103.0.5060.53-2 but the next release should include the patch again
