### ISSUE TITLE
update OBS repo

### ISSUE THREAD

**Issue by Dimev** [ungoogled-software/ungoogled-chromium-archlinux#168]
Looks like the last build for the OBS version for arch was 10 months ago, might be smart to make a new one?

**Comment by networkException** [comment]
10 months? The last build got submitted 22 hours ago: https://build.opensuse.org/package/show/home:ungoogled_chromium/ungoogled-chromium-arch

**Comment by Dimev** [comment]
Oh lol sorry, was looking at the testing one
