### ISSUE TITLE
Crash on launch due to glibc version mismatch [Manjaro]

### ISSUE THREAD

**Issue by yakovuvarov** [ungoogled-software/ungoogled-chromium-archlinux#169]
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.2.3
Codename:	Qonos

98.0.4758.102-2 fails to launch due to being linked against glibc 2.34. This is a consequence of Arch having too few maintainers to work on a toolchain, including glibc, and Manjaro inheriting pretty much all of the toolchain from Arch. As a result, this breaks the package -- at least, for Manjaro users.

glibc 2.35 is kind of available for Manjaro users should they install it manually from Arch's testing (https://lists.archlinux.org/pipermail/arch-dev-public/2022-February/030729.html), and I see that Arch maintainers already built 2.35 package (https://archlinux.org/packages/core/x86_64/glibc), but it'll be at least a few months before Manjaro will roll out regular update -- and the package will remain broken for the time being.

Is there an option to go back to 2.33 for the time being? My hardware is not that great, and while I can build from source, I'd really hate to waste half a day each time in order to compile another update.

**Comment by networkException** [comment]
98.0.4758.102-2 is linked against glibc 2.35-2 (both OBS and GitHub Release). This project generall assumes a fully updated Arch Linux install, if Manjaro lacks behind there's not a whole lot that can be done.

The effort to build a CI system for Manjaro just for some short lived dependency differences is not really justified at the moment, if Manjaro would differ in other ways or dependency versions are different for a long time (over months) that would change of course.

**Comment by yakovuvarov** [comment]
I see. Thanks for the detailed reply, closing the issue.
