### ISSUE TITLE
Make systemd optional? 

### ISSUE THREAD

**Issue by Wastelander72** [ungoogled-software/ungoogled-chromium-archlinux#171]
Hi, I'm trying to install the package on Obarun, an Arch-based build without systemd. However, it fails because systemd is a required dependancy and I have to manually remove it from the list or use the "--assume-installed=systemd" option every time that a new version is available. Would it be possible to remove the dependancy or at least make it optional? The browser seems to work without issues on my distro, systemd does not seem to be really necessary. Thanks in advance.

**Comment by networkException** [comment]
The package provided by this repository is supposed to be a drop in replacement for `extra/chromium`. Maintaining a release for an Arch derivative is as such currently not in scope.

Honestly adding `--assume-installed=systemd` does not sound like much of a pain (compared to outdated dependencies on Manjaro for example), you could add the argument to an alias for pacman in your shell config.

**Comment by Wastelander72** [comment]
thanks a bunch, I will try this
