### ISSUE TITLE
incorrect version display 

### ISSUE THREAD

**Issue by shaeinst** [ungoogled-software/ungoogled-chromium-archlinux#172]
just upgraded to version [99.0.4844.51-1](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/tag/99.0.4844.51-1). But it shows version [98.0.4758.102-2](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/tag/98.0.4758.102-2) on chromium about page
![image](https://user-images.githubusercontent.com/41078534/156936308-0c0cdcd3-2d45-4f8f-92bf-85b75aedd3a8.png)
![image](https://user-images.githubusercontent.com/41078534/156936389-f458701c-d0ac-4826-bc1b-f5ee5ec93fa8.png)

**Comment by networkException** [comment]
You installed the debug package instead of the actual one

**Comment by shaeinst** [comment]
my silly mistake. But why it's showing 98 though? i mean debug package is 99

**Comment by networkException** [comment]
Debug packages only provide additional information for debugging tools on top of the actual binaries, they do not provide the executables themselves
