### ISSUE TITLE
restore [block] media/autoplay flag

### ISSUE THREAD

**Issue by redurgam** [ungoogled-software/ungoogled-chromium-archlinux#174]
quite late, but would it be possible to reinstate code that was featured and then removed?

"Chrome 61 is out! Autoplay policy is now available via the chrome flag." Sept 6 2017
"Ultimately this switch got removed and the autoplay blocking in Chromium/chrome is back to being half or at times not working at all." Nov 24 2019

maybe there's another way around this issue

**Comment by jstkdng** [comment]
At this point that old code could be using apis that have changed or are no longer available and I don't think anyone here wants or is capable of maintaining that old code. Your best option would be to create an extension to achieve what you want.

**Comment by networkException** [comment]
See https://github.com/Eloston/ungoogled-chromium/pull/1565
