### ISSUE TITLE
ICU 70

### ISSUE THREAD

**Issue by arjpar** [ungoogled-software/ungoogled-chromium-archlinux#179]
When I try to run ungoogled chromium from the command line I get:
```
/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.70: cannot open shared object file: No such file or directory
```

This does not happen with normal (googled) Chromium.

The latest version of ICU is 71.1-1 (in the arch repos), I think the Ungoogled Chromium binary (from Chaotic AUR *and* OBS) still uses ICU 70. Is it possible to bump up the ICU version to ICU 71? 

Thank you so much for your help!

**Comment by angelsl** [comment]
ICU 71 was just released to Arch repos 12 hours ago. But yes, Ungoogled Chromium needs to be rebuilt.

**Comment by networkException** [comment]
Yes the OBS repo still had ICU 70 cached, I need to trigger another rebuild

**Comment by sys-256** [comment]
I've encountered the same issue, and until a new build has been published, you can use this solution:
- Download the ICU 70 binaries with `wget https://github.com/unicode-org/icu/releases/download/release-70-1/icu4c-70_1-Ubuntu-20.04-x64.tgz`.
- Extract the tarball and cd into the directory with `tar -xf icu4c-70_1-Ubuntu-20.04-x64.tgz; cd icu/usr/local/lib`.
- Copy the shared libraries to `/usr/lib` with `sudo cp *.so.70 /usr/lib`.

Done, I hope this worked for you as well!

**Comment by networkException** [comment]
The OBS package just finished building. I'll close this issue once GitHub Actions is done as well
