### ISSUE TITLE
Update AUR package // 75.0.3770.80-1 tag?

### ISSUE THREAD

**Issue by flawedworld** [ungoogled-software/ungoogled-chromium-archlinux#18]
AUR package is still on 72.0.3626.122-1.

**Comment by nikolowry** [comment]
@seppiofish maintains `ungoogled-chromium` on AUR. I attempted to notify them in #1, but didn't receive a reply

**Comment by seppiofish** [comment]
@flawedworld @nikolowry updated today, please refer to #1

**Comment by wchen342** [comment]
Hi, I am a little confused about the current status of AUR packages. There are now two packages, `ungoogled-chromium` and `ungoogled-chromium-archlinux`. Which one is supposed to be updated regularly? Which one is the formal one?

**Comment by Eloston** [comment]
@wchen342 `ungoogled-chromium` is the original and "official" one (i.e. referenced in the READMEs and such). I think we should consolidate to `ungoogled-chromium` in the end.
