### ISSUE TITLE
Missing pre-built binaries for armv7, armv8 and riscv64

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [ungoogled-software/ungoogled-chromium-archlinux#181]
In the Open Suse builds, I definitely miss armv7, armv8/aarch64 and riscv64. In case all those platforms are too much overhead, I would propose to add at lease aarch64 builds.

**Comment by networkException** [comment]
Arch Linux [doesn't support](https://wiki.archlinux.org/title/Frequently_asked_questions#What_architectures_does_Arch_support?) architectures other than x86_64

**Comment by jstkdng** [comment]
The OBS only supports building for Arch on x86_64. While there are projects to support Archlinux on arm and riscv (does chromium even support riscv?) devices, they can't be built on the OBS.

**Comment by braewoods** [comment]
We do provide ARM builds on the Debian / Ubuntu packaging but this packaging is only for mainline Arch which only supports x86_64. Unless OBS starts supporting those other Arch based projects, this is how it shall be for the foreseeable future.
