### ISSUE TITLE
Manjaro Crash on Launch: /usr/lib/chromium/chromium: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/chromium/chromium)

### ISSUE THREAD

**Issue by IkerGimenez** [ungoogled-software/ungoogled-chromium-archlinux#183]
Good news: looks like Manjaro updated and the issue with the ICU library in #180 is solved.
Bad news: looks like the GCC libraries are out of sync. 

Thought you would like a heads up before you're flooded with support requests.

Downgrading to version  101.0.4951.54-1 works as a workaround.

**Comment by gw2princeps** [comment]
For people coming here and asking how to downgrade: 
1. Download [101.0.4951.54-1](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/tag/101.0.4951.54-1) 
2. Run `sudo pacman -U ungoogled-chromium-101.0.4951.54-1-x86_64.pkg.tar.zst`

**Comment by IkerGimenez** [comment]
Manjaro Stable was updated and now the GCC libraries are in sync.
