### ISSUE TITLE
Backporting 16kb page size patch for Arch/Asahi Linux on Apple ARM64

### ISSUE THREAD

**Issue by derzahla** [ungoogled-software/ungoogled-chromium-archlinux#184]
I have tried with my limited skillset to backport the following patch to the latest versions of ungoogled chromium and so far have had no success:

https://chromium-review.googlesource.com/c/chromium/src/+/3545665

Sorry if this is out of scope, but I was hoping someone smarter than me has had any luck constructing a working PKGBUILD for Apple ARM64  either backporting , or using  the latest unstable chromium  source

**Comment by networkException** [comment]
What part are you struggling with?

**Comment by derzahla** [comment]
@networkException It's been awhile since I tried it so I went back through using the newest version. The problem seems to be that it keeps defaulting to it's built in tools that dont work.  Bu

**Comment by networkException** [comment]
I've heard about 102 fixing this, please report back after the release if you were able to get a build :)

**Comment by derzahla** [comment]
Yes, 102 fixes it.  Thanks
