### ISSUE TITLE
Add Cirrus CI checks

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-archlinux#2]
Borrow code from `ungoogled-chromium-debian` as necessary.

**Comment by Eloston** [comment]
efd1194f6cc3ffe67bf6cce9c4aac356b18dd632 adds some code borrowed from other platforms, but it doesn't work because this repo doesn't use a submodule for the ungoogled-chromium repo. So, we need some way to determine which commit of the ungoogled-chromium repo to use. However, the solution will depend on how we ultimately decide to reformat the PKGBUILD in #1.

**Comment by nikolowry** [comment]
Thoughts on switching to an Archlinux image (https://hub.docker.com/r/archlinux/base) and adding another task in https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/master/.cirrus.yml that resembles the following (using longhand options for `makepkg` for explicitness):

```yml
validate_pkgbuild_task:
    makepkg_script:
        - makepkg --cleanbuild --syncdeps --nobuild
```

If running builds doesn't result in costs/fees, it be even better to omit the `--nobuild` option. But building on every commit might be overwhelming, so maybe just run those on tags/releases?

Note: I've never used Cirrus, so apologizes if anything in the example `yml` isn't valid

**Comment by Eloston** [comment]
@nikolowry I like that idea. Running builds won't result in costs/fees, but I believe there are one or more storage, RAM, or time restrictions that would prevent builds from completing. If you don't want to add Cirrus CI to your account, I believe you can make a PR against this repo to test it.

**Comment by nikolowry** [comment]
I've been offline for a vacation, I'll give it a shot on my forked repo this week.

**Comment by Eloston** [comment]
This is already done.
