### ISSUE TITLE
Import archlinux jsoncpp bugfix  

### ISSUE THREAD

**Issue by a61kt** [ungoogled-software/ungoogled-chromium-archlinux#203]
Could u import  archlinux  chromium  json cpp bugfix
https://github.com/archlinux/svntogit-packages/commit/bf2401407df5bcc938382eb03748fbef41e41c89

**Comment by networkException** [comment]
I will once that actually ends up in the extra repo

**Comment by networkException** [comment]
Resolved in https://github.com/ungoogled-software/ungoogled-chromium-archlinux/commit/8f1495f810dadc97abf4a5f397d16762f041abfc
