### ISSUE TITLE
Log-In and preferences cookies are abnormally deleted automatically

### ISSUE THREAD

**Issue by foss-aash** [ungoogled-software/ungoogled-chromium-archlinux#207]
## OS

Manjaro Linux x86_64
GNOME 42.5

## Installed via:

Open Build Service Repository

## Version

Version 107.0.5304.110 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

## Description of the problem

When I connect to a web service (like GitHub) or when I save my preferences on a website (like a search engine) the cookies used for this disappear as soon as I close ungoogled-chromium.

## Additional informations

The only settings I have changed are the theme, my default search engine and the startup page. Other than that the basic settings are the same.

**Comment by networkException** [comment]
Sounds like you just need to disable "Clear cookies and site data when you close all windows" in chrome://settings/cookies

**Comment by foss-aash** [comment]
Yes indeed 
Sorry I just installed ungoogled-chromium and I completely forgot this detail 😅️

Sorry again for this unnecessary bug report (since there was no bug)
