### ISSUE TITLE
Can't start since latest re2 package update

### ISSUE THREAD

**Issue by ajmxco** [ungoogled-software/ungoogled-chromium-archlinux#210]
Going from re2 (1:20220601-1 -> 1:20221201-1) yesterday gives the following error when trying to launch:

/usr/lib/chromium/chromium: error while loading shared libraries: libre2.so.9: cannot open shared object file: No such file or directory

Here's some context on arch forum:

https://bbs.archlinux.org/viewtopic.php?id=281869

I'm using https://aur.archlinux.org/packages/ungoogled-chromium-bin and my fix was to back out of the re2 update.

**Comment by Absolutely-Free** [comment]
I am seeing this issue as well. It is occurring with both the OBS version of the package as well as the AUR version.

**Comment by ptr1337** [comment]
ungoogled-chromium needs to be recompiled against the re2 update.

**Comment by networkException** [comment]
A rebuild for this is already in process as 108.0.5359.94-2, see https://github.com/ungoogled-software/ungoogled-chromium-archlinux/commit/10c3d866220a9df1e36bc3b1896c5ac2d0509d1a

**Comment by ajmxco** [comment]
Thanks for the fix and works great now.
