### ISSUE TITLE
Stack smashing detected on certain webpage

### ISSUE THREAD

**Issue by jastx-jasmint** [ungoogled-software/ungoogled-chromium-archlinux#216]
Hi, sorry if this isn't quite the right place to post this. I'm not sure where else to put this other than on the main repo, but that didn't quite seem right either as it seems they would rather people post in their specific supported platform issues list first.

Whenever I open a certain webpage (https://auspost.com.au/parcel-send or https://auspost.com.au/just-send-it, both should be the same thing), I get a page with a dead folder that says 'aw snap' with the error code 64000. When chromium is run through the terminal, accessing this page leads to this output:
`*** stack smashing detected ***: terminated`

**Things I've tried:**
- Clearing cache, browsing history etc through the browser settings (same issue)
- Opening the page as a new user (same issue)
- Opening the page using Google Chrome (works)
- Opening the page through a Windows VM on the same machine using Ungoogled Chromium (works)
- Reinstalling the package after deleting package cache and configs using Stacer and `sudo pacman -Rns` (same issue)
- Restarting after reinstalling (same issue)
- Deleting the chromium folder under ~/.config/ (same issue)
- Checking if the same issue exists on a different desktop user (still exists)
- Removing /etc/chromium and reinstalling (same issue)

I'm quite new to Linux and have never run into this type of issue before that wasn't fixed with a cache clear on Windows. Any help and/or pointers in the right direction appreciated :)

[System info](https://gist.github.com/jastx-jasmint/d15dc65ae9595fee702d074065a3ab4b)
Ungoogled Chromium was installed from the chaotic-AUR, in case that makes any difference.

**Comment by PF4Public** [comment]
Did you build it from source or was it a binary?

**Comment by jastx-jasmint** [comment]
It's a binary from the Chaotic-AUR. I also notified them about the issue, and someone told me that compiling in a tool such as FORTIFY_SOURCE (or the unholy Google AddressSanitiser) could be a solution.
The question then becomes, is it up to the binary maintainer to compile it in, or should I create an issue on the main repo about this? 🤔

**Comment by SuperPrower** [comment]
Similar issue, crashes on a lot of websites, like GitHub notification page, sometimes Youtube, etc. Tried downgrading to version 108, didn't help.

**Comment by SuperPrower** [comment]
Seems to have improved for me with the latest update, didn't get any crashes for now.

**Comment by jastx-jasmint** [comment]
Interesting, the latest update fixed it for me too ^^ I'll close this then, but will reopen if it ever starts happening again.
