### ISSUE TITLE
upgrade from Chromium possible ?

### ISSUE THREAD

**Issue by SvenMeyer** [ungoogled-software/ungoogled-chromium-archlinux#218]
I have Chromium installed, quite a few profiles and installed extensions, would like to switch to 
ungoogled-chromium.

However if I follow the install guideline I am asked if I want to replace Chromium.

```
$ sudo pacman -S ungoogled-chromium
resolving dependencies...
looking for conflicting packages...
:: ungoogled-chromium and chromium are in conflict. Remove chromium? [y/N] 
```

What happens if I say "y", will my installed profiles and extension stay ?
... or would I have to reinstall everything ?

Btw, if I start the AppImage (with the idea to have ungoogled-chromium alongside the original Chromium install), then I get only the original Chromium.

**Comment by PF4Public** [comment]
> What happens if I say "y", will my installed profiles and extension stay ?
> ... or would I have to reinstall everything ?

Everything should stay, but I would suggest you to backup the whole Chromium profile just in case.

**Comment by networkException** [comment]
Replacing the package will merely replace the binary and some libraries, your profiles should be entirely unaffected

**Comment by SvenMeyer** [comment]
Gave it a try and looks like it just worked and did not loose anything.
Installed extension and configuration are still there :+1:

**Comment by SvenMeyer** [comment]
Maybe this information should be added to the README in the install section (or Q&A).

**Comment by PF4Public** [comment]
AFAICT saved passwords could become unreadable for new binary, so check that.
