### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by wchen342** [ungoogled-software/ungoogled-chromium-archlinux#22]
The newest version cannot start on a Nvidia+Intel GPU notebook. If I have `libva-vdpau-driver` installed, startup fails with `GPU at BusId 0x1 doesn't have a supported video decoder`; if I uninstall `libva-vdpau-driver`, it fails with `[21560:21560:0807/204751.670679:ERROR:vaapi_wrapper.cc(326)] vaInitialize failed: unknown libva error`.
It used to be a warning which will not crash the whole thing, but now it just crashes.

**Comment by wchen342** [comment]
I built on a second machine with `use_vaapi=false` but the package crashes on both machines. The vaapi error disappeared but it still crashes with `Illegal instruction (core dumped)`. Verbose log does not really have anything useful:
```
[1782:1782:0807/235617.143497:VERBOSE1:breakpad_linux.cc(1994)] Breakpad disabled
[1:1:0807/235617.273246:INFO:cpu_info.cc(53)] Available number of cores: 8
[1:1:0807/235617.273476:VERBOSE1:zygote_main_linux.cc(217)] ZygoteMain: initializing 0 fork delegates
[1782:1782:0807/235617.381429:VERBOSE1:webrtc_event_log_manager.cc(89)] WebRTC remote-bound event logging enabled.
[1782:1782:0807/235617.381689:VERBOSE1:proxy_config_service_linux.cc(1243)] Obtained proxy settings from annotation hash code 11258689
[1782:1782:0807/235617.381722:VERBOSE1:pref_proxy_config_tracker_impl.cc(184)] 0xbe8ad17a920: set chrome proxy config service to 0xbe8ad13a200
[1782:1808:0807/235617.489168:WARNING:backend_impl.cc(1846)] Destroying invalid entry.
[1782:1782:0807/235617.496474:WARNING:account_consistency_mode_manager.cc(250)] Desktop Identity Consistency cannot be enabled as no OAuth client ID and client secret have been configured.
[1782:1782:0807/235617.497680:WARNING:account_consistency_mode_manager.cc(250)] Desktop Identity Consistency cannot be enabled as no OAuth client ID and client secret have been configured.
[1782:1782:0807/235617.497836:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(347)] MutablePO2TS::MutablePO2TS
[1782:1782:0807/235617.497862:WARNING:account_consistency_mode_manager.cc(250)] Desktop Identity Consistency cannot be enabled as no OAuth client ID and client secret have been configured.
[1807:1807:0807/235617.685022:VERBOSE1:sandbox_linux.cc(69)] Activated seccomp-bpf sandbox for process type: gpu-process.
[1812:1812:0807/235619.002753:VERBOSE1:statistics_recorder.cc(409)] Collections of all histograms
Histogram: ChildProcess.FieldTrials.CreateFromShmemSuccess recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: ThreadPool.DetachDuration.ContentChild.Foreground recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.HeartbeatLatencyMicroseconds.ContentChild.BackgroundTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.HeartbeatLatencyMicroseconds.ContentChild.BackgroundTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.HeartbeatLatencyMicroseconds.ContentChild.UserBlockingTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.HeartbeatLatencyMicroseconds.ContentChild.UserBlockingTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.HeartbeatLatencyMicroseconds.ContentChild.UserVisibleTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.HeartbeatLatencyMicroseconds.ContentChild.UserVisibleTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumActiveWorkers.ContentChild.Foreground recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksBeforeDetach.ContentChild.Foreground recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksBetweenWaits.ContentChild.Foreground recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksRunWhileQueuing.ContentChild.BackgroundTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksRunWhileQueuing.ContentChild.BackgroundTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksRunWhileQueuing.ContentChild.UserBlockingTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksRunWhileQueuing.ContentChild.UserBlockingTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksRunWhileQueuing.ContentChild.UserVisibleTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksRunWhileQueuing.ContentChild.UserVisibleTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumWorkers.ContentChild.Foreground recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.TaskLatencyMicroseconds.ContentChild.BackgroundTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.TaskLatencyMicroseconds.ContentChild.BackgroundTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.TaskLatencyMicroseconds.ContentChild.UserBlockingTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.TaskLatencyMicroseconds.ContentChild.UserBlockingTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.TaskLatencyMicroseconds.ContentChild.UserVisibleTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.TaskLatencyMicroseconds.ContentChild.UserVisibleTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: V8.Initializer.LoadV8Snapshot.Result recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: V8.Initializer.OpenV8File.Result recorded 2 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (2 = 100.0%)
1  ... 


[1807:1807:0807/235619.004065:VERBOSE1:statistics_recorder.cc(409)] Collections of all histograms
Histogram: ChildProcess.FieldTrials.CreateFromShmemSuccess recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: GPU.CollectContextGraphicsInfo recorded 2 samples, mean = 34.5 (flags = 0x1)
0   ... 
12  ------------------------------------------------------------------------O (1 = 50.0%) {0.0%}
14  ... 
48  -----------------------------O                                            (1 = 50.0%) {50.0%}
57  ... 

Histogram: GPU.GLImplementation recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ... 

Histogram: GPU.InitializeOneOffMediumTime recorded 1 samples, mean = 129.0 (flags = 0x1)
0    ... 
113  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
139  ... 

Histogram: GPU.MaxMSAASampleCount recorded 2 samples (flags = 0x1)
32  ------------------------------------------------------------------------O (2 = 100.0%)

Histogram: GPU.Sandbox.InitializedSuccessfully recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: ThreadPool.DetachDuration.ContentChild.Foreground recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.HeartbeatLatencyMicroseconds.ContentChild.BackgroundTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.HeartbeatLatencyMicroseconds.ContentChild.BackgroundTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.HeartbeatLatencyMicroseconds.ContentChild.UserBlockingTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.HeartbeatLatencyMicroseconds.ContentChild.UserBlockingTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.HeartbeatLatencyMicroseconds.ContentChild.UserVisibleTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.HeartbeatLatencyMicroseconds.ContentChild.UserVisibleTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumActiveWorkers.ContentChild.Foreground recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksBeforeDetach.ContentChild.Foreground recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksBetweenWaits.ContentChild.Foreground recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksRunWhileQueuing.ContentChild.BackgroundTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksRunWhileQueuing.ContentChild.BackgroundTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksRunWhileQueuing.ContentChild.UserBlockingTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksRunWhileQueuing.ContentChild.UserBlockingTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksRunWhileQueuing.ContentChild.UserVisibleTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumTasksRunWhileQueuing.ContentChild.UserVisibleTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.NumWorkers.ContentChild.Foreground recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.TaskLatencyMicroseconds.ContentChild.BackgroundTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.TaskLatencyMicroseconds.ContentChild.BackgroundTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.TaskLatencyMicroseconds.ContentChild.UserBlockingTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.TaskLatencyMicroseconds.ContentChild.UserBlockingTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.TaskLatencyMicroseconds.ContentChild.UserVisibleTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: ThreadPool.TaskLatencyMicroseconds.ContentChild.UserVisibleTaskPriority_MayBlock recorded 0 samples (flags = 0x1)
0 ... 


Illegal instruction (core dumped)
```

@Eloston Is this the same as [https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/20](https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/20)?

**Comment by Eloston** [comment]
> Is this the same as ungoogled-software/ungoogled-chromium-debian#20?

I haven't looked into the issue further yet. However, I wouldn't be surprised if it's related to the new VA-API patch.

**Comment by outloudvi** [comment]
ungoogled-chromium also crashed on my computer (also, Intel + NVIDIA notebook) from recently, while [chromium-vaapi](https://aur.archlinux.org/packages/chromium-vaapi/) is working (hardware acceleration unavailable, though).

On running ungoogled-chromium, I receive:
```
[8573:8573:0809/203624.123947:ERROR:vaapi_wrapper.cc(326)] vaInitialize failed: unknown libva error
[8573:8573:0809/203624.145839:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
```

regardless of `libva-vdpau-driver` installed or not (nvidia driver not used with [nvidia-xrun](https://wiki.archlinux.org/index.php/nvidia-xrun)).

On nvidia driver enabled and `libva-vdpau-driver` installed, I get:
```
[12210:12210:0809/203937.068940:ERROR:vaapi_wrapper.cc(704)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[12210:12210:0809/203937.069005:ERROR:vaapi_wrapper.cc(595)] FillProfileInfo_Locked failed for va_profile 0 and entrypoint 1
[12210:12210:0809/203937.069011:ERROR:vaapi_wrapper.cc(704)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[12210:12210:0809/203937.069014:ERROR:vaapi_wrapper.cc(595)] FillProfileInfo_Locked failed for va_profile 1 and entrypoint 1
[12210:12210:0809/203937.069017:ERROR:vaapi_wrapper.cc(704)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[12210:12210:0809/203937.069019:ERROR:vaapi_wrapper.cc(595)] FillProfileInfo_Locked failed for va_profile 2 and entrypoint 1
[12210:12210:0809/203937.069022:ERROR:vaapi_wrapper.cc(704)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[12210:12210:0809/203937.069025:ERROR:vaapi_wrapper.cc(595)] FillProfileInfo_Locked failed for va_profile 3 and entrypoint 1
[12210:12210:0809/203937.069028:ERROR:vaapi_wrapper.cc(704)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[12210:12210:0809/203937.069031:ERROR:vaapi_wrapper.cc(595)] FillProfileInfo_Locked failed for va_profile 5 and entrypoint 1
[12210:12210:0809/203937.069034:ERROR:vaapi_wrapper.cc(704)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[12210:12210:0809/203937.069037:ERROR:vaapi_wrapper.cc(595)] FillProfileInfo_Locked failed for va_profile 6 and entrypoint 1
[12210:12210:0809/203937.069042:ERROR:vaapi_wrapper.cc(704)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[12210:12210:0809/203937.069064:ERROR:vaapi_wrapper.cc(595)] FillProfileInfo_Locked failed for va_profile 7 and entrypoint 1
[12210:12210:0809/203937.069068:ERROR:vaapi_wrapper.cc(704)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[12210:12210:0809/203937.069071:ERROR:vaapi_wrapper.cc(595)] FillProfileInfo_Locked failed for va_profile 8 and entrypoint 1
[12210:12210:0809/203937.069075:ERROR:vaapi_wrapper.cc(704)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[12210:12210:0809/203937.069078:ERROR:vaapi_wrapper.cc(595)] FillProfileInfo_Locked failed for va_profile 9 and entrypoint 1
[12210:12210:0809/203937.069082:ERROR:vaapi_wrapper.cc(704)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[12210:12210:0809/203937.069086:ERROR:vaapi_wrapper.cc(595)] FillProfileInfo_Locked failed for va_profile 10 and entrypoint 1
[12210:12210:0809/203937.069090:ERROR:vaapi_wrapper.cc(425)] GetConfigAttributes failed for va_profile 5
[12210:12210:0809/203937.069094:ERROR:vaapi_wrapper.cc(425)] GetConfigAttributes failed for va_profile 6
[12210:12210:0809/203937.069097:ERROR:vaapi_wrapper.cc(425)] GetConfigAttributes failed for va_profile 7
```

On nvidia driver enabled and `libva-vdpau-driver` uninstalled, I get:
```
[15925:15925:0809/204018.685238:ERROR:vaapi_wrapper.cc(326)] vaInitialize failed: unknown libva error
```

**Comment by wchen342** [comment]
The crash actually had nothing to do with vaapi. I tried `ungoogled-crhomium` on an Intel only notebook but it still crashes. Then I tried `chromium-vaapi` from AUR and it didn't crash. So there must be a faulty patch somewhere else.
I am trying to use gdb to determine where the crash happens but I cannot seem to trigger the crash when gdb is attached..

**Comment by Eloston** [comment]
You're right, it was a hasty assumption. I'm also experimenting with build flags and patches, and I don't think VA-API is at fault either. Right now, I'm trying to get a debug build to work, but I'm running into linker issues with the fingerprinting patch at the moment.

Since GDB prevents the issue from occuring, it may have something to do with the compiler optimizations producing invalid code. I'm hoping that the debug builds will be more strict and allow the compiler or linker to catch problems with the code.

**Comment by outloudvi** [comment]
I also agree that there may be some patching problems rather than VA-API since [google-chrome](https://aur.archlinux.org/packages/google-chrome/) is working on my computer.

**Comment by wchen342** [comment]
I figured it out. Changing `use_allocator="none"` to `use_allocator="tcmalloc"` fixed the crash. Based on core dump the error comes from `GlibcGetSizeEstimate` in `base/allocator/allocator_shim_default_dispatch_to_glibc.cc` and it has something to do with shim headers. According to `tools/generate_shim_headers/generate_shim_headers.py` in an offical build they should not be used, but `use-system-libraries-in-official-build.patch` changed that behavior.

I do not know C++ good enough to figure out the root cause of this. I think it may have something to do with something like glibc versions.

**Comment by Eloston** [comment]
Nice work. Unfortunately, this area is also beyond my knowledge; it's not necessarily a C++ issue at this point, but more of an understanding of OS internals.

More importantly, I'm not comfortable with just changing `use_allocator` to solve the problems. Our current setup is an unsupported use-case (i.e. using system libraries with `is_official_build`), and I don't think it's worth our time to try and hack it simply for a little performance improvement (at least for me). I'm going to remove explicit settings for `is_official_build` and `use_allocator` so we can let the code decide the best options here (and also the shim headers patch).

**Comment by thefallenrat** [comment]
With the removal of `use-system-libraries-in-official-build.patch`, the build fails with the following messages: 
```
[2019-08-10T13:55:26.913Z] In file included from ../../base/i18n/icu_util.cc:21:
[2019-08-10T13:55:26.913Z] gen/shim_headers/icuuc_shim/third_party/icu/source/common/unicode/putil.h:3:2: error: shim headers must not be used in official builds!
[2019-08-10T13:55:26.913Z] #error shim headers must not be used in official builds!
[2019-08-10T13:55:26.913Z]  ^
[2019-08-10T13:55:26.913Z] In file included from ../../base/i18n/icu_util.cc:22:
[2019-08-10T13:55:26.913Z] gen/shim_headers/icuuc_shim/third_party/icu/source/common/unicode/udata.h:3:2: error: shim headers must not be used in official builds!
[2019-08-10T13:55:26.913Z] #error shim headers must not be used in official builds!
[2019-08-10T13:55:26.913Z]  ^
[2019-08-10T13:55:26.913Z] In file included from ../../base/i18n/icu_util.cc:24:
[2019-08-10T13:55:26.913Z] gen/shim_headers/icui18n_shim/third_party/icu/source/i18n/unicode/timezone.h:3:2: error: shim headers must not be used in official builds!
[2019-08-10T13:55:26.913Z] #error shim headers must not be used in official builds!
[2019-08-10T13:55:26.913Z]  ^
[2019-08-10T13:55:26.913Z] 3 errors generated.
```
Is there something wrong on my end, @Eloston ?

**Comment by Eloston** [comment]
@thefallenrat Might be fine now, but I don't have an environment to test it.

**Comment by wchen342** [comment]
@thefallenrat  make sure `is_official_build` is `false` otherwise it won't build.

**Comment by jstkdng** [comment]
I have tested this pkgbuild from my fork of this repo and it's built succesfully. I added some stuff that was removed though. Me reasoning is that, if it works for the archlinux maintainers, why wouldn't it work for us?
https://github.com/jstkdng/ungoogled-chromium-archlinux
Could send a PR if @Eloston is alright with my changes.

**Comment by thefallenrat** [comment]
Here's my [PKGBUILD](https://gitea.artixlinux.org/packagesU/ungoogled-chromium/src/branch/master/trunk/PKGBUILD) at the moment. It was based on the PKGBUILD made by `seppia` at [the AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ungoogled-chromium). The PKGBUILD was only modified to update the archlinux version to the latest commit (7f34e64), [just like @Eloston  did](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/commit/aaff7802c435881920c3e09f670c6ad375b95359). And it failed with the messages that I posted above

> make sure is_official_build is false otherwise it won't build.

Should I do that? I mean, @Eloston removed the flags altogether (Even though I'm sure that's the main reason why the build fails). Nevertheless, I'll add `is_official_build=false` anyway just to see what happens

If all else fails, guess I might try `PKGBUILD` by @jstkdng provided if he explained the reasoning behind the changes he made

**Comment by jstkdng** [comment]
@thefallenrat 
I actually sort of re added the patch that was removed. Instead of using a patch file the arch maintainers just used sed to achieve the same thing the patch file did.
And I built without the is_official_build flag and it built succesfully, of course, it was a developer build, but hey, if it works for the maintainers why wouldn't it work for us?
pic related
![image](https://user-images.githubusercontent.com/52050345/62828046-68459f00-bba2-11e9-8b76-a402fc036231.png)
I also added the vaapi fix from chromium-vaapi to enable hardware acceleration and removed the bundled vaapi patch which was basically useless.

**Comment by wchen342** [comment]
@thefallenrat It is not PKGBUILD that caused the error you see but GN flags. The error you see comes from `generate_shim_headers.py` which adds a section in headers, and the section will only be triggered when `OFFICIAL_BUILD` is defined (i.e. `is_official_build` is `true`). When `is_official_build` is removed it should be defaulted to `false` but in case something else changed it to true implicitly it is better to define it as `false`.

@jstkdng Are you using tag `76.0.3809.100-1` from main repo? @Eloston removed `is_debug=false` from GN flags which will cause it to be defaulted to `true`.

**Comment by jstkdng** [comment]
@wchen342 
yes, I'm using that tag, but I have my own fork in which I re-added that option for testing. I haven't tested the build without it but seriously don't want to spend 6 hours compiling again, too lazy for that.
The arch's chromium pkgbuild doesn't have that option either:
![image](https://user-images.githubusercontent.com/52050345/62828191-8eb90980-bba5-11e9-97e5-0a7caf2845cf.png)
Then again, if it works for them, it should work for us right? I have my fork with that mentality in mind.

**Comment by wchen342** [comment]
@jstkdng I see `is_official_build=true` in your screenshot, which will turn `is_debug` off automatically. And sure, a debug build can work but I don't think letting users use a debug build is a good idea (only my personal opinion).

**Comment by jstkdng** [comment]
@wchen342 
I have is_official_build=true in my fork's flags and supposedly is_debug is false, but in my previous screenshot it says "Developer Build"
Pic related
![image](https://user-images.githubusercontent.com/52050345/62828439-08ec8c80-bbac-11e9-9aba-801af46aafef.png)
And the previous screenshot
![image](https://user-images.githubusercontent.com/52050345/62828046-68459f00-bba2-11e9-8b76-a402fc036231.png)

**Comment by thefallenrat** [comment]
Thanks, @wchen342. With the added [`is_official_build=false` flag](https://gitea.artixlinux.org/packagesU/ungoogled-chromium/commit/f1e7a12ca318c3c8438d1c1b9b61c5330cc2894b), the packages were built and ran successfully

**Comment by wchen342** [comment]
@jstkdng I just built a previous version using seppia's AUR package and it definitely says `Official Build`. I am not sure what was going on with your build. Probably you can try to run `gn args -C out/Default --list` to see whether the flags are really set correctly.

**Comment by jstkdng** [comment]
@wchen342 
That command returned and error related to python so no use, this are my resulting flags.gn
Kinda weird tbh, now there is no is_official_build and is_debug is there as false.
Oh well, at least it works. Will test later tomorrow with is_official_build=true. Hope it doesn't break.
```
clang_use_chrome_plugins=false
closure_compile=false
enable_hangout_services_extension=false
enable_hevc_demuxing=true
enable_mdns=false
enable_mse_mpeg2ts_stream_parser=true
enable_nacl=false
enable_nacl_nonsfi=false
enable_one_click_signin=false
enable_reading_list=false
enable_remoting=false
enable_reporting=false
enable_service_discovery=false
enable_swiftshader=false
enable_widevine=true
exclude_unwind_tables=true
fieldtrial_testing_like_official_build=true
google_api_key=""
google_default_client_id=""
google_default_client_secret=""
optimize_webui=false
safe_browsing_mode=0
treat_warnings_as_errors=false
use_official_google_api_keys=false
use_unofficial_version_number=false

blink_symbol_level=0
custom_toolchain="//build/toolchain/linux/unbundle:default"
enable_ac3_eac3_audio_demuxing=true
enable_iterator_debugging=false
fatal_linker_warnings=false
ffmpeg_branding="ChromeOS"
gold_path=""
goma_dir=""
host_toolchain="//build/toolchain/linux/unbundle:default"
is_clang=true
is_debug=false
jumbo_file_merge_limit=8
link_pulseaudio=true
linux_use_bundled_binutils=false
proprietary_codecs=true
symbol_level=0
use_cups=true
use_custom_libcxx=false
use_gio=true
use_gnome_keyring=false
use_jumbo_build=true
use_kerberos=false
use_libjpeg_turbo=true
use_lld=true
use_openh264=false
use_pulseaudio=true
use_sysroot=false
use_system_freetype=true
use_system_harfbuzz=true
use_system_lcms2=true
use_system_libjpeg=true
use_system_libopenjpeg2=true
use_system_zlib=true
use_vaapi=true
```

**Comment by Eloston** [comment]
The flags I've removed from the main ungoogled-chromium repo are now in `flags.archlinux.gn`. There should be no effective changes to the GN flags, unless the PKGBUILD is using the wrong ungoogled-chromium version.

Right now, it seems using `is_official_build=true` with system libraries will break things unless the memory allocator is set to `tcmalloc` (the default on desktop Linux). I should note that using `is_official_build=true` with system libraries was never supported by Chromium to begin with, so it's hard to say how this workaround may break in the future.

**Comment by thefallenrat** [comment]
> The flags I've removed from the main ungoogled-chromium repo are now in `flags.archlinux.gn`. 

But you [removed it (`is_official_build=false`) altogether ](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/commit/7f34e646009e66258e3d567728d0ac209ea7556c). At least add this flag for this platform please

**Comment by jstkdng** [comment]
Just finished compiling and building with only is_official_build=true, works for me. Pic related.
I have release the resulting package in my [repo](https://repo.vin.ovh/arch/x86_64/ungoogled-chromium-76.0.3809.100-2-x86_64.pkg.tar.xz) is anyone wants to test it.
Using only that flag reduced the package size so maybe there is indeed a difference.
![image](https://user-images.githubusercontent.com/52050345/62833636-b04add00-bc07-11e9-9644-555345fd6f61.png)

**Comment by Eloston** [comment]
@thefallenrat You don't need to add `is_official_build=false` because it's never set to true anywhere in this repo or the ungoogled-chromium repo.

**Comment by thefallenrat** [comment]
@Eloston Oh you're right. Guess I'll have to point it to the latest commit
