### ISSUE TITLE
Not opening after update to 111.0.5563.64-1

### ISSUE THREAD

**Issue by PistachioGuy** [ungoogled-software/ungoogled-chromium-archlinux#221]
I'm getting this error:

/usr/lib/chromium/chromium: error while loading shared libraries: libavcodec.so.59: cannot open shared object file: No such file or directory

**Comment by PF4Public** [comment]
Duplicate of #220

**Comment by PistachioGuy** [comment]
Yeah I kind of noticed that after I posted it

**Comment by networkException** [comment]
Closing in favor of #220
