### ISSUE TITLE
Cannot launch after update - Manjaro KDE

### ISSUE THREAD

**Issue by bagaweb** [ungoogled-software/ungoogled-chromium-archlinux#222]
Error when launching:

`/usr/lib/chromium/chromium: error while loading shared libraries: libavcodec.so.60: cannot open shared object file: No such file or directory`

How can I solve this error?

Tried to downgrade but got another error:

`errore: '/var/cache/pacman/pkg/ungoogled-chromium-110.0.5481.177-1-x86_64.pkg.tar.zst': il pacchetto non è valido oppure è corrotto (firma PGP)`

**Comment by networkException** [comment]
Manjaro doesn't have ffmpeg 6 yet, see #220. You need to download the -1 package manually `wget https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/download/111.0.5563.64-1/ungoogled-chromium-111.0.5563.64-1-x86_64.pkg.tar.zst` and install it using `pacman -U ungoogled-chromium-111.0.5563.64-1-x86_64.pkg.tar.zst`

**Comment by bagaweb** [comment]
Thank you very much @networkException !!!

You saved my day :)
