### ISSUE TITLE
VA-API Hardware decoding is broken :( 

### ISSUE THREAD

**Issue by Ph0rk0z** [ungoogled-software/ungoogled-chromium-archlinux#223]
Updated to v108. FFmpeg went to 6.0. Now can't downgrade UGC any longer.

I browsed the arch va-api thread and it seems like there are issues getting decoding working.  They say you need vulkan, but vulkan doesn't detect any codecs because I am on haswell. Support is "incomplete".

Currently, I believe I have all the flags set since it worked before. It tries to load vda decoder and returns `VDA error 4`.
It then falls back to FFmpeg and begins frying eggs on the CPU. Tried to downgrade libva to 2.16 but no profiles are detected either.

Upgraded to v111 and it does the same thing. 

Am I missing something or am I SOL?

**Comment by jstkdng** [comment]
VAAPI still works with libva-mesa-driver on my end. You might be getting left behind as software improves. RIP. Does VAAPI on firefox work?

**Comment by emansom** [comment]
Haswell is EOL and will not receive much maintenance from Intel developers. They will likely break compatibility.

If hardware allows, your best course is to buy a RX 6400 and use the AMDGPU kernel driver with libva-mesa instead, smooth sailing from there.

Intel Arc A380 is a good deal as well and works stellar with latest Mesa, kernel, firmware etc. Though, has some lackluster power management (40W at idle) currently.

NOVIDEO, well, [no](https://youtu.be/19jUboon5gI).

**Comment by Ph0rk0z** [comment]
Can't do that, it's a T440P. And a new machine has sealed slab design and many soldered components.

I found the culprit: https://bbs.archlinux.org/viewtopic.php?id=283012

Now it won't let me use 108 but 111 is working. Seems strange and I guess 20-30% cpu is better than 80-100%.
