### ISSUE TITLE
release notes / documentation for 111.0.5563.110-1

### ISSUE THREAD

**Issue by SvenMeyer** [ungoogled-software/ungoogled-chromium-archlinux#225]
It would be great to mention within the release notes if 111.0.5563.110-1 still requires ffmpeg 6 , in which case Version 111.0.5563.64-1 would be the last version to work on current Majaro stable.

**Comment by networkException** [comment]
I don't use Manjaro, I can only point out something like that when I specifically know a runtime dependency changed (so in .64-2)
