### ISSUE TITLE
upgraded to 113.0.5672.63-1 on Manjaro stable > CRASH : version `GLIBCXX_3.4.31' not found

### ISSUE THREAD

**Issue by SvenMeyer** [ungoogled-software/ungoogled-chromium-archlinux#227]
system : Manjaro Linux stable 

Just upgraded to 113.0.5672.63-1 and got this error

```
$ chromium
/usr/lib/chromium/chromium: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /usr/lib/chromium/chromium)
```
![image](https://user-images.githubusercontent.com/25609/236384317-bb1f62e6-e97a-4348-b050-3e0ac328998c.png)

**Comment by SvenMeyer** [comment]
tried to downgrade as it is still in my cache, but did not work for me ...

```
$ sudo pacman -U file:///var/cache/pacman/pkg/ungoogled-chromium-112.0.5615.165-1-x86_64.pkg.tar.zst
[sudo] password for sum: 
loading packages...
error: '/var/cache/pacman/pkg/ungoogled-chromium-112.0.5615.165-1-x86_64.pkg.tar.zst': invalid or corrupted package (PGP signature)
``

**Comment by ptr1337** [comment]
I think this is due it got rebuild against gcc 13.
You could fetch the latest version from the releases probably

**Comment by bagaweb** [comment]
Same error here, how did you solve?

```
$ chromium
/usr/lib/chromium/chromium: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /usr/lib/chromium/chromium)
```

**Comment by SvenMeyer** [comment]
@bagaweb As I do not want to leave the Manjaro core stable branch (I need my computer to work on other stuff) and I do not want to switch off signature verification (I need all the security I can get (easily)), I just use the Appimage for now until this issue is resolved "somehow". I can't spent too much time on it anymore ...

**Comment by SvenMeyer** [comment]
> I think this is due it got rebuild against gcc 13. You could fetch the latest version from the releases probably

I am honestly just a "Linux user" (although I am a developer), but isn't that a bit "problematic" that I have to have gcc/libs 13 installed to get it to work? Why isn't that included in chromium?
Current Manjaro core stable does not offer gcc 13 for now, and I do not want to switch to unstable/develop ...
Latest AUR also does not work
Any other options?

**Comment by bagaweb** [comment]
> @bagaweb As I do not want to leave the Manjaro core stable branch (I need my computer to work on other stuff) and I do not want to switch off signature verification (I need all the security I can get (easily)), I just use the Appimage for now until this issue is resolved "somehow". I can't spent too much time on it anymore ...

Alright thanks @SvenMeyer I will try your solution and hopefully this issue will be solved soon.

**Comment by SvenMeyer** [comment]
resolved with the latest update for Manjaro stable from 2023-06-04
