### ISSUE TITLE
Last release version does not match last Appimage version

### ISSUE THREAD

**Issue by SvenMeyer** [ungoogled-software/ungoogled-chromium-archlinux#229]
Why is the last release [113.0.5672.126-1](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/tag/113.0.5672.126-1)

... but the last Appimage (already) [113.0.5672.127-1](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/appimage/64bit/113.0.5672.127-1) ?

**Comment by networkException** [comment]
Because the person who built the AppImage didn't pay attention to the release notes in https://github.com/ungoogled-software/ungoogled-chromium/releases/tag/113.0.5672.127-1 and packaged a Windows only release. It probably won't cause issues, it also isn't good practice however.
