### ISSUE TITLE
Broken after libevent 2.1.11-1 update due to soname bump

### ISSUE THREAD

**Issue by inde3d** [ungoogled-software/ungoogled-chromium-archlinux#23]
chromium fails to launch with the following error after updating libevent from 2.1.10-1 to 2.1.11.-1 due to the soname being bumped from 6 to 7.

`/usr/lib/chromium/chromium: error while loading shared libraries: libevent-2.1.so.6: cannot open shared object file: No such file or directory`

Package built from ungoogled-chromium-archlinux on AUR, version 76.0.3809.100-1.

**Comment by jstkdng** [comment]
you have to recompile chromium for it to be linked to the new version of libevent.

**Comment by inde3d** [comment]
Wait, is that it? I've always thought that soname updates required a package update... I'm embarrassed.

Sorry if I wasted anyone's time!
