### ISSUE TITLE
ICU link outdated (.72 -> .73)

### ISSUE THREAD

**Issue by realSaddy** [ungoogled-software/ungoogled-chromium-archlinux#230]
Good day,

ICU SO version 73 is released, breaking current upstream installs. OBS didn't
seem to ingest this change for the most recent build. Could you run a 
re-build @networkException ?

Thank you,
Jack

**Comment by networkException** [comment]
sure yea

**Comment by jab416171** [comment]
Is this rebuild running now? Or has it finished?

**Comment by playgithub** [comment]
can't wait, I've built it using https://aur.archlinux.org/packages/ungoogled-chromium,
It works with ICU 73

The news said that github action services has been down temporarily  yesterday,
maybe it's the reason why the action was cancelled: https://github.com/ungoogled-software/ungoogled-chromium-archlinux/actions/runs/5414664373

**Comment by amiria703** [comment]
To be able to run ungoogled-chromium before this problem fixes, install `icu72` from AUR.
If you're using yay as your AUR helper:
```yay -Sy icu72```

**Comment by networkException** [comment]
By now it should've been rebuilt everywhere

**Comment by SvenMeyer** [comment]
My problem is that I do not have ICU73 on my Manjaro Linux (Cinnamon) system which break it for me , see https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/231

@amiria703 Can I just install it doing `yay -Sy icu73` ?

**Comment by amiria703** [comment]
> @amiria703 Can I just install it doing `yay -Sy icu73` ?

No. icu73 doesn't exist in AUR. but AFAIK you can build icu package and install it but I'm not sure whether it makes conflicts with Manjaro packages or not.
More info: https://unix.stackexchange.com/questions/70495#454178
Also: https://wiki.archlinux.org/title/Arch_build_system#Usage
