### ISSUE TITLE
error while loading shared libraries: libicui18n.so.73

### ISSUE THREAD

**Issue by SvenMeyer** [ungoogled-software/ungoogled-chromium-archlinux#231]
My system : Manjaro Linux

I just upgraded to the latest AUR (..-bin) version 114.0.5735.198-2 and got the following error

```
$ chromium
/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.73:
cannot open shared object file: No such file or directory
```

**Comment by jordischoots** [comment]
Have you updated the [icu](https://archlinux.org/packages/core/x86_64/icu/) package?

**Comment by networkException** [comment]
Manjaro users need to downgrade to -1 until icu gets updated in the manjaro repos.

Please note again that this repository is not designed to support manjaro and compatibility is best effort only
