### ISSUE TITLE
build failed manjaro 64bit

### ISSUE THREAD

**Issue by d4vid1** [ungoogled-software/ungoogled-chromium-archlinux#24]
1 warning generated.
[10198/21130] ACTION //third_party/dom...uild/toolchain/linux/unbundle:default)
FAILED: pyproto/third_party/dom_distiller_js/dom_distiller_pb2.py gen/third_party/dom_distiller_js/dom_distiller.pb.h gen/third_party/dom_distiller_js/dom_distiller.pb.cc gen/third_party/dom_distiller_js/dom_distiller_json_converter.h 
/usr/bin/python2 ../../tools/protoc_wrapper/protoc_wrapper.py dom_distiller.proto --protoc ./protoc --proto-in-dir ../../third_party/dom_distiller_js/dist/proto --cc-out-dir gen/third_party/dom_distiller_js --py-out-dir pyproto/third_party/dom_distiller_js --plugin ../../third_party/dom_distiller_js/protoc_plugins/json_values_converter.py --plugin-out-dir gen/third_party/dom_distiller_js --plugin-options output_dir=:
Traceback (most recent call last):
  File "../../third_party/dom_distiller_js/protoc_plugins/json_values_converter.py", line 14, in <module>
    from util import plugin_protos, types, writer
  File "/home/david/.cache/yay/ungoogled-chromium-archlinux/src/chromium-76.0.3809.100/third_party/dom_distiller_js/protoc_plugins/util/plugin_protos.py", line 22, in <module>
    from google.protobuf.descriptor_pb2 import FieldDescriptorProto
ImportError: No module named protobuf.descriptor_pb2
--plugin_out: protoc-gen-plugin: Plugin failed with status code 1.
Protoc has returned non-zero status: 1
[10203/21130] CXX obj/third_party/cld_3/src/src/cld_3/fml_parser.o
ninja: build stopped: subcommand failed.
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...

**Comment by wchen342** [comment]
@d4vid1 Try [this](https://forums.gentoo.org/viewtopic-t-1086154-start-0.html).

**Comment by d4vid1** [comment]
> @d4vid1 Try [this](https://forums.gentoo.org/viewtopic-t-1086154-start-0.html).

thanks bro

i found some solution [here](https://stackoverflow.com/questions/44278582/failed-to-install-protobuf-using-pip3)

i use:
sudo pacman -S python-pip ; sudo pip install --upgrade --ignore-installed tensorflow google-apputils gsutil

build fine now!

**Comment by Eloston** [comment]
Issue looks solved, closing.
