### ISSUE TITLE
There is a compile issue on ARM (not spam. bro why u pulling the 1984 card here)

### ISSUE THREAD

**Issue by euiwerpoirwiop** [ungoogled-software/ungoogled-chromium-archlinux#243]
Using my patched PKGBUILD (with Arch ARM's patches) from https://raw.githubusercontent.com/euiwerpoirwiop/test/main/PKGBUILD" i get this error "[5511/55967] CC obj/third_party/libaom...eon_i8mm/compound_convolve_neon_i8mm.o
FAILED: obj/third_party/libaom/libaom_intrinsics_neon_i8mm/compound_convolve_neon_i8mm.o
clang -MMD -MF obj/third_party/libaom/libaom_intrinsics_neon_i8mm/compound_convolve_neon_i8mm.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -I../../third_party/libaom/source/config -I../../third_party/libaom/source/config/linux/arm64-cpu-detect -I../../third_party/libaom/source/libaom -march=armv8.2-a+dotprod+i8mm -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -ffp-contract=off -flto=thin -fsplit-lto-unit -fwhole-program-vtables -mbranch-protection=standard --target=aarch64-linux-gnu -mno-outline -ffile-compilation-dir=. -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wno-unused-variable -Wno-c++11-narrowing -Wno-unused-but-set-variable -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecated-builtins -Wno-bitfield-constant-conversion -Wno-deprecated-this-capture -std=c11 -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -march=armv8.5-a -mtune=apple-m1 -O3 -pipe -fstack-protector-strong -fno-plt -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -Wno-builtin-macro-redefined -Wno-unknown-warning-option -c ../../third_party/libaom/source/libaom/av1/common/arm/compound_convolve_neon_i8mm.c -o obj/third_party/libaom/libaom_intrinsics_neon_i8mm/compound_convolve_neon_i8mm.o
../../third_party/libaom/source/libaom/av1/common/arm/compound_convolve_neon_i8mm.c:30:19: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve4_4_2d_h' that is compiled without support for 'i8mm'
int32x4_t sum = vusdotq_lane_s32(horiz_const, permuted_samples, x_filter, 0);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/av1/common/arm/compound_convolve_neon_i8mm.c:52:12: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_2d_h' that is compiled without support for 'i8mm'
sum[0] = vusdotq_lane_s32(horiz_const, permuted_samples[0], x_filter, 0);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/av1/common/arm/compound_convolve_neon_i8mm.c:53:12: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_2d_h' that is compiled without support for 'i8mm'
sum[0] = vusdotq_lane_s32(sum[0], permuted_samples[1], x_filter, 1);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/av1/common/arm/compound_convolve_neon_i8mm.c:55:12: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_2d_h' that is compiled without support for 'i8mm'
sum[1] = vusdotq_lane_s32(horiz_const, permuted_samples[1], x_filter, 0);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/av1/common/arm/compound_convolve_neon_i8mm.c:56:12: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_2d_h' that is compiled without support for 'i8mm'
sum[1] = vusdotq_lane_s32(sum[1], permuted_samples[2], x_filter, 1);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/av1/common/arm/compound_convolve_neon_i8mm.c:237:19: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve4_4_x' that is compiled without support for 'i8mm'
int32x4_t sum = vusdotq_lane_s32(round_offset, permuted_samples, x_filter, 0);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/av1/common/arm/compound_convolve_neon_i8mm.c:259:12: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_x' that is compiled without support for 'i8mm'
sum[0] = vusdotq_lane_s32(round_offset, permuted_samples[0], x_filter, 0);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/av1/common/arm/compound_convolve_neon_i8mm.c:260:12: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_x' that is compiled without support for 'i8mm'
sum[0] = vusdotq_lane_s32(sum[0], permuted_samples[1], x_filter, 1);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/av1/common/arm/compound_convolve_neon_i8mm.c:262:12: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_x' that is compiled without support for 'i8mm'
sum[1] = vusdotq_lane_s32(round_offset, permuted_samples[1], x_filter, 0);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/av1/common/arm/compound_convolve_neon_i8mm.c:263:12: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_x' that is compiled without support for 'i8mm'
sum[1] = vusdotq_lane_s32(sum[1], permuted_samples[2], x_filter, 1);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
10 errors generated.
[5513/55967] CC obj/third_party/libaom...cs_neon_i8mm/aom_convolve8_neon_i8mm.o
FAILED: obj/third_party/libaom/libaom_intrinsics_neon_i8mm/aom_convolve8_neon_i8mm.o
clang -MMD -MF obj/third_party/libaom/libaom_intrinsics_neon_i8mm/aom_convolve8_neon_i8mm.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -I../../third_party/libaom/source/config -I../../third_party/libaom/source/config/linux/arm64-cpu-detect -I../../third_party/libaom/source/libaom -march=armv8.2-a+dotprod+i8mm -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -ffp-contract=off -flto=thin -fsplit-lto-unit -fwhole-program-vtables -mbranch-protection=standard --target=aarch64-linux-gnu -mno-outline -ffile-compilation-dir=. -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wno-unused-variable -Wno-c++11-narrowing -Wno-unused-but-set-variable -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecated-builtins -Wno-bitfield-constant-conversion -Wno-deprecated-this-capture -std=c11 -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -march=armv8.5-a -mtune=apple-m1 -O3 -pipe -fstack-protector-strong -fno-plt -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -Wno-builtin-macro-redefined -Wno-unknown-warning-option -c ../../third_party/libaom/source/libaom/aom_dsp/arm/aom_convolve8_neon_i8mm.c -o obj/third_party/libaom/libaom_intrinsics_neon_i8mm/aom_convolve8_neon_i8mm.o
../../third_party/libaom/source/libaom/aom_dsp/arm/aom_convolve8_neon_i8mm.c:60:9: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_4_usdot' that is compiled without support for 'i8mm'
sum = vusdotq_lane_s32(vdupq_n_s32(0), permuted_samples[0], filter, 0);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/aom_dsp/arm/aom_convolve8_neon_i8mm.c:61:9: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_4_usdot' that is compiled without support for 'i8mm'
sum = vusdotq_lane_s32(sum, permuted_samples[1], filter, 1);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/aom_dsp/arm/aom_convolve8_neon_i8mm.c:83:10: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_usdot' that is compiled without support for 'i8mm'
sum0 = vusdotq_lane_s32(vdupq_n_s32(0), permuted_samples[0], filter, 0);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/aom_dsp/arm/aom_convolve8_neon_i8mm.c:84:10: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_usdot' that is compiled without support for 'i8mm'
sum0 = vusdotq_lane_s32(sum0, permuted_samples[1], filter, 1);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/aom_dsp/arm/aom_convolve8_neon_i8mm.c:86:10: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_usdot' that is compiled without support for 'i8mm'
sum1 = vusdotq_lane_s32(vdupq_n_s32(0), permuted_samples[1], filter, 0);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/aom_dsp/arm/aom_convolve8_neon_i8mm.c:87:10: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_usdot' that is compiled without support for 'i8mm'
sum1 = vusdotq_lane_s32(sum1, permuted_samples[2], filter, 1);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/aom_dsp/arm/aom_convolve8_neon_i8mm.c:217:9: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_4_usdot_partial' that is compiled without support for 'i8mm'
sum = vusdotq_lane_s32(vdupq_n_s32(0), samples_lo, filter, 0);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/aom_dsp/arm/aom_convolve8_neon_i8mm.c:218:9: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_4_usdot_partial' that is compiled without support for 'i8mm'
sum = vusdotq_lane_s32(sum, samples_hi, filter, 1);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/aom_dsp/arm/aom_convolve8_neon_i8mm.c:234:10: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_usdot_partial' that is compiled without support for 'i8mm'
sum0 = vusdotq_lane_s32(vdupq_n_s32(0), samples0_lo, filter, 0);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/aom_dsp/arm/aom_convolve8_neon_i8mm.c:235:10: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_usdot_partial' that is compiled without support for 'i8mm'
sum0 = vusdotq_lane_s32(sum0, samples0_hi, filter, 1);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/aom_dsp/arm/aom_convolve8_neon_i8mm.c:237:10: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_usdot_partial' that is compiled without support for 'i8mm'
sum1 = vusdotq_lane_s32(vdupq_n_s32(0), samples1_lo, filter, 0);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
../../third_party/libaom/source/libaom/aom_dsp/arm/aom_convolve8_neon_i8mm.c:238:10: error: always_inline function 'vusdotq_s32' requires target feature 'i8mm', but would be inlined into function 'convolve8_8_usdot_partial' that is compiled without support for 'i8mm'
sum1 = vusdotq_lane_s32(sum1, samples1_hi, filter, 1);
^
/usr/lib/clang/16/include/arm_neon.h:35961:15: note: expanded from macro 'vusdotq_lane_s32'
__ret_157 = vusdotq_s32(__s0_157, __s1_157, (int8x16_t)(splatq_lane_s32(*(int32x2_t *) &__reint_157, __p3_157))); \
^
12 errors generated.
[5519/55967] ACTION //third_party/devt...uild/toolchain/linux/unbundle:default)"  is there a problem with my PKGBUILD or a toolchain problem and patches are at https://github.com/archlinuxarm/PKGBUILDs/tree/master/extra/chromium and they are 0001-0003 and the PKGBUILD mods from there, is there a patch that fixes this on arm linux

Fully Updated
Asahi Arch Linux ARM
CPU M1
Kernel: 6.4.0-asahi-10-1-edge-ARCH

**Comment by networkException** [comment]
You have been ban evading multiple times now, I don't think I will include those patches. If you really believe you need to come back in 3 days with a new account I would recommend to format your issue in a way that doesn't spam the whole tracker.

Besides, this repository never promised to support ALARM, I currently cannot test or produce builds for that platform.

Also I do not wish to be referred to as "bro"
