### ISSUE TITLE
PKGBUILD sha256sum for ungoogled-chromium mismatch

### ISSUE THREAD

**Issue by Stephen-Seo** [ungoogled-software/ungoogled-chromium-archlinux#244]
The sha256sum for `ungoogled-chromium-117.0.5938.88-1.tar.gz` is listed in the PKGBUILD as `0b55e77d0e507bd0901ef46ec1d6e065012c75c31e997e7db465b9fb471b82e9` but the sha256sum (for me) appears to be `97d67f4783702537355cdfcaad67024413102478ec5a431b2d51b454e8baea33` instead.

**Comment by networkException** [comment]
Yep you're right, I made a mistake while refactoring the script that outputs this hash
