### ISSUE TITLE
error while loading shared libraries: libdav1d.so.6 >> 117.0.5938.149-1

### ISSUE THREAD

**Issue by olmet** [ungoogled-software/ungoogled-chromium-archlinux#246]
Have today made an update to the following version:

ungoogled-chromium-bin 117.0.5938.149-1
https://aur.archlinux.org/packages/ungoogled-chromium-bin

Chromium no longer starts, the error message appears:

/usr/lib/chromium/chromium: error while loading shared libraries: libdav1d.so.6: cannot open shared object file: No such file or directory

What can I do?

System:
OS: Arch Linux x86_64 
Kernel: 6.1.55-1-lts 
Shell: zsh 5.9 
Plasma 5.27.8

**Comment by ptr1337** [comment]
> Have today made an update to the following version:
> 
> ungoogled-chromium-bin 117.0.5938.149-1 https://aur.archlinux.org/packages/ungoogled-chromium-bin
> 
> Chromium no longer starts, the error message appears:
> 
> /usr/lib/chromium/chromium: error while loading shared libraries: libdav1d.so.6: cannot open shared object file: No such file or directory
> 
> What can I do?
> 
> System: OS: Arch Linux x86_64 Kernel: 6.1.55-1-lts Shell: zsh 5.9 Plasma 5.27.8

You need to wait for a rebuild. dav1d got updated few minutes ago.

**Comment by lucaslira95** [comment]
Still not working :/

**Comment by benthetechguy** [comment]
Four days is a long time to have something as important as a browser package completely broken. Please rebuild

**Comment by olmet** [comment]
Yesterday, the update to the new version arrived, and now everything is working again.

ungoogled-chromium-bin-117.0.5938.149-2

**Comment by benthetechguy** [comment]
I upgraded to the same version, and it's still not working for me (same error).
