### ISSUE TITLE
Error downloading, 404 returned

### ISSUE THREAD

**Issue by Rithdev** [ungoogled-software/ungoogled-chromium-archlinux#256]
The URL provided by github that is used in the PKGBUILD for the aur script will return a 404 when downloading the tarball
"ungoogled-chromium-120.0.6099.216-2-x86_64.pkg.tar.zst"
### Why?
For some reason (i'm not really that smart and i'm yet learning git) the download URL corresponds to 
"https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/download/120.0.6099.216-1/ungoogled-chromium-120.0.6099.216-2-x86_64.pkg.tar.zst" instead of "https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/download/120.0.6099.216-2/ungoogled-chromium-120.0.6099.216-2-x86_64.pkg.tar.zst" (the version string has a -1 instead of the -2 of the actual release), making the script fail once it has to download the required file.

**Comment by KnechtNoobrecht** [comment]
Can confirm

**Comment by networkException** [comment]
Unfortunately this will take another rebuild until the AUR will hopefully fix itself

**Comment by jasursadikov** [comment]
Same on my end:
```
==> ERROR: Failure while downloading https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/download/120.0.6099.216-2/ungoogled-chromium-120.0.6099.216-2-x86_64.pkg.tar.zst
    Aborting...
 -> error making: ungoogled-chromium-bin-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
ungoogled-chromium-bin - exit status 1
```

**Comment by networkException** [comment]
I am responsible for the mistake, I tagged an outdated commit, GitHub Actions is responsible for the rebuild talking so long.

I'm not familiar enough with `yay` to answer that, sorry

**Comment by networkException** [comment]
Can someone affected by this confirm whether the update worked? I tested this on my Arch machine and it worked fine, but the helper never saw the broken release there.

**Comment by dan-m8t** [comment]
My AUR helper (paru) still reports 404:

```
Aur (1) ungoogled-chromium-bin-120.0.6099.216-1

:: Proceed with installation? [Y/n]: y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
fetching devel info...
==> Making package: ungoogled-chromium-bin 120.0.6099.216-2 (Fri Jan 12 22:36:31 2024)
==> Retrieving sources...
  -> Downloading ungoogled-chromium-120.0.6099.216-2-x86_64.pkg.tar.zst...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/download/120.0.6099.216-2/ungoogled-chromium-120.0.6099.216-2-x86_64.pkg.tar.zst
    Aborting...
error: failed to download sources for 'ungoogled-chromium-bin-120.0.6099.216-1': 
error: packages failed to build: ungoogled-chromium-bin-120.0.6099.216-1
```

**Comment by Whyhow314** [comment]
I had to delete the cached version, but after that it worked fine.

**Comment by dan-m8t** [comment]
> I had to delete the cached version, but after that it worked fine.

I can confirm this.

**Comment by KnechtNoobrecht** [comment]
> I had to delete the cached version, but after that it worked fine.

How do i do this?
`pacman -Sc` did not work for me.

**Comment by Whyhow314** [comment]
There might be a way directly with paru, but I just deleted the directory `~/.cache/paru/clone/ungoogled-chromium-bin` (or renaming it would probably work)

**Comment by dan-m8t** [comment]
`paru -Sc` should do the trick afaik:

```
Clone Directory: /home/dan/.cache/paru/clone
:: Do you want to clean all other AUR packages from cache? [Y/n]: n

Diff Directory: /home/dan/.cache/paru/diff
:: Do you want to remove all saved diffs? [Y/n]: n
```

Same as `yay` btw - otherweise simply delete the directory as suggested.

**Comment by KnechtNoobrecht** [comment]
> There might be a way directly with paru, but I just deleted the directory `~/.cache/paru/clone/ungoogled-chromium-bin` (or renaming it would probably work)

That works. Thanks.

**Comment by Rithdev** [comment]
As stated by other users, the problem is now solved and if it still throws a 404 at you, just clear your aur helper cache or delete the clone directory altogether so it downloads everything again, marking as closed
