### ISSUE TITLE
⚡️ Enhancement - Prevent setting as default Web Browser after update

### ISSUE THREAD

**Issue by Rikj000** [ungoogled-software/ungoogled-chromium-archlinux#260]
## Issue Description
Since a recent update [`ungoogle-chromium-bin`](https://aur.archlinux.org/packages/ungoogled-chromium-bin)
started setting itself as the default browser after each update (on KDE Plasma).

It quickly gets very annoying to always go to:
Settings => Applications => Default Applications => Toggle Web browser
back to what was manually configured before the update.

I already reported this here: https://aur.archlinux.org/packages/ungoogled-chromium-bin#comment-959023

## Possible solutions
I did some digging and can present x3 possible solutions,   
but I still have to monitor if they will stick after next update.

### 1. Disable policy `DefaultBrowserSettingEnabled`

By disabling the `DefaultBrowserSettingEnabled` policy,   
we should be able to stop Chromium from ever attempting to set itself as default.

**Sources:**
- https://www.chromium.org/administrators/linux-quick-start/#set-up-policies
- https://chromeenterprise.google/policies/?policy=DefaultBrowserSettingEnabled

**Policy Description:**
Setting the policy to True has Google Chrome always check whether it's the default browser on startup and,   
if possible, automatically register itself.   
Setting the policy to False stops Google Chrome from ever checking if it's the default and turns user controls off for this option.

1. Create the directory:
```bash
sudo mkdir -p /etc/chromium/policies/managed/
```
2. Create the policy file:
```bash
sudo touch /etc/chromium/policies/managed/test_policy.json
```
3. Edit the policy file:
```bash
sudo nano /etc/chromium/policies/managed/test_policy.json
```
4. Paste following contents and save:
```json
{
  "DefaultBrowserSettingEnabled": false
}
```

### 2. Set `--no-default-browser-check` runtime flag

By setting the `--no-default-browser-check` runtime flag,   
we should be able to stop Chromium from prompting to be set as the default browser

**Runtime Flag Description:**
Disable the default browser check, do not prompt to set it as such

**Sources:**
- https://github.com/GoogleChrome/chrome-launcher/blob/main/docs/chrome-flags-for-tools.md#commonly-unwanted-browser-features
- https://unix.stackexchange.com/questions/110613/how-can-i-make-chrome-stop-asking-to-be-the-default-browser/608042#608042

1. Open the `chromium.desktop` file:
```bash
sudo nano /usr/share/applications/chromium.desktop
```
2. Alter the `Exec` line and save:
```desktop
Exec=/usr/bin/chromium --no-default-browser-check %U
```

### 3. Set `default_browser_infobar_last_declined` to a high value

By altering `default_browser_infobar_last_declined` to a high value,   
we should hopefully be able to stop Chromium from ever asking to be set as default.

**Sources:**
- https://serverfault.com/questions/1120674/how-to-prevent-the-chrome-default-browser-prompt-and-welcome-screen-using-master

1. Open the `Preferences` file
```bash
nano /home/<username>/.config/chromium/Default/Preferences
```
2. Alter the `default_browser_infobar_last_declined` value to `99999999999999999` and save

## Environment
| Software | Version |
| --- | --- |
| Ungoogled Chromium | 122.0.6261.94 |
| KDE Plasma | 5.27.10 |
| Kernel | 6.7.7-x64v2-xanmod1-1 |

**Comment by Rikj000** [comment]
I'm guessing the issue is more KDE related :thinking: 
Since today the default Web Browser got reset back to `ungoogled-chromium-bin` **again**..

Even though `ungoogled-chromium-bin` has not / did not receive an update   
since I've opened this issue / applied above described possible solutions.

**Comment by networkException** [comment]
Is this Plasma 6 specific perhaps?

**Comment by Rikj000** [comment]
Closing this issue since I'm rather certain that it's KDE related by now.

**Comment by 45mg** [comment]
I have this issue, and I'm not using KDE.

**Comment by Rikj000** [comment]
I think I finally resolved my issue by opening `/home/<username>/.config/mimeapps.list`,   
and removing each occurrence of `chromium.desktop;`
