### ISSUE TITLE
Newest release update issue due to bad source code link.

### ISSUE THREAD

**Issue by UX0l0l** [ungoogled-software/ungoogled-chromium-archlinux#267]
I tried updating ungoogled-chromium-bin on my arch install but it gave me this error message:
`==> ERROR: Failure while downloading https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/download/125.0.6422.60-1/ungoogled-chromium-125.0.6422.60-1-x86_64.pkg.tar.zst`

This piqued my curiosity and I decided to investigate the error myself. Turns out, the actual link on the releases page here on the github page is https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/download/125.0.6422.60/ungoogled-chromium-125.0.6422.60-1-x86_64.pkg.tar.zst, while in the PKGBUILD (as shown in the error) it is https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/download/125.0.6422.60-1/ungoogled-chromium-125.0.6422.60-1-x86_64.pkg.tar.zst

You may not notice the difference, but the link on the github releases page actually lacks the package release (**_125.0.6422.60_**) while the PKGBUILD link has the release (**_125.0.6422.60-1_**) meaning the links are ever so slightly different, causing the error

I hope you are able to fix this issue soon

**Comment by mikkasendke** [comment]
same issue here (obviously) I'd love to see this resolved as well, thank you :)

**Comment by networkException** [comment]
argh sorry, got the tag name wrong. I'll push a fix

**Comment by UX0l0l** [comment]
thx a lot :)

**Comment by networkException** [comment]
not sure if aur helpers can handle the manual fix, a build for -2 is running tho

**Comment by UX0l0l** [comment]
I think I figured out the reason for this and an easy fix that doesn't involve any AUR or PKGBUILD changes.

If you go to the tags, you'll notice the latest release doesn't have the format (pkgver-pkgrel) like in the PKGBUILD, but simply (pkgver). All the previous releases have the (pkgver-pkgrel) format as their names except this one. Here's screenshots to explain what I mean:

### Latest release:
![Screenshot_20240521_104145_GitHub.jpg](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/assets/47756363/17f269e8-3812-4998-ab2d-7893d5b84585)


### The release before it:
![Screenshot_20240521_104216_GitHub.jpg](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/assets/47756363/4c84b9f5-1a62-451d-ac42-f0fa45fed8da)

### PKGBUILD before and after:
![Screenshot_20240521_104803_Bromite.jpg](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/assets/47756363/d4b5845a-8131-4306-936d-da24a26275a6)

Simply revert the PKGBUILD to what it was but add "-1" at the end of the release name on github and that should solve the issue 100% and not cause any inconsistency with previous releases
