### ISSUE TITLE
error during patch phase

### ISSUE THREAD

**Issue by Brli** [ungoogled-software/ungoogled-chromium-archlinux#270]
```
INFO: * Applying missing-dependencies.patch (1/106)
patching file chrome/browser/extensions/BUILD.gn
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file chrome/browser/extensions/BUILD.gn.rej
patching file chrome/common/BUILD.gn
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file chrome/common/BUILD.gn.rej
patching file content/browser/BUILD.gn
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file content/browser/BUILD.gn.rej
patching file services/passage_embeddings/BUILD.gn
Traceback (most recent call last):
  File "/build/ungoogled-chromium/src/ungoogled-chromium-126.0.6478.55-1/utils/patches.py", line 257, in <module>
    main()
  File "/build/ungoogled-chromium/src/ungoogled-chromium-126.0.6478.55-1/utils/patches.py", line 253, in main
    args.callback(args, parser.error)
  File "/build/ungoogled-chromium/src/ungoogled-chromium-126.0.6478.55-1/utils/patches.py", line 204, in _apply_callback
    apply_patches(generate_patches_from_series(patch_dir, resolve=True),
  File "/build/ungoogled-chromium/src/ungoogled-chromium-126.0.6478.55-1/utils/patches.py", line 138, in apply_patches
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
```

it seems to be in conflicts with [ninja-out-of-order-generation-fix.patch](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/master/ninja-out-of-order-generation-fix.patch)

Also, the pkgbuild of this repo is out-of-sync with what's offered in [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ungoogled-chromium）

**Comment by PF4Public** [comment]
> it seems to be in conflicts with [ninja-out-of-order-generation-fix.patch](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/master/ninja-out-of-order-generation-fix.patch)

Both patches serve the same purpose.

**Comment by networkException** [comment]
Ah, my bad, I forgot that this is now included upstream.

> Also, the pkgbuild of this repo is out-of-sync with what's offered in [AUR]

the non -bin aur version is maintained by someone else

**Comment by ptr1337** [comment]
> the non -bin aur version is maintained by someone else

The package is generally poorly and slow maintained. If you the AUR maintainer of it, would be interested to give someone co-maintainer - we would welcome it.

**Comment by jstkdng** [comment]
>The package is generally poorly

rude

>and slow maintained

that might be true, but that happens when the maintainers are volunteers and it can happen to anyone

>If you the AUR maintainer of it, would be interested to give someone co-maintainer - we would welcome it.

I'm actually a co-maintainer and handled everything before @networkException came in. I think it'd be better to integrate the OBS workflow for the AUR as well. We'd need to ask seppia (https://aur.archlinux.org/account/seppia) to give maintainer to us or just fill an orphan request.

**Comment by networkException** [comment]
Looks like the maintainance status got transferred fully?

I guess we'll adjust the CI here to just push this repo to the AUR minus some folders and with a .SRCINFO

**Comment by jstkdng** [comment]
we need another user and add that user's ssh key here.

**Comment by networkException** [comment]
for `-bin` I use my personal account's ssh key (which isn't used anywhere else)

**Comment by jstkdng** [comment]
alright then, just added your account.

**Comment by networkException** [comment]
> inb4 jia tan 2.0

:( /lh

(with what's publically accessible online about me that'd be a pretty bad idea though lol)

I added a new CI step and pushed a new tag, looks good so far. I copied things that looked important from the other PKGBUILD, feel free to add things back if needed though.
