### ISSUE TITLE
No binaries

### ISSUE THREAD

**Issue by jamescraft10** [ungoogled-software/ungoogled-chromium-archlinux#286]
I've been compiling this for 10 hours. Where are the binaries for ungoggled chromium?

**Comment by networkException** [comment]
It takes more than 24 hours

**Comment by networkException** [comment]
Also like, its already done? See https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/tag/129.0.6668.70-3

**Comment by jamescraft10** [comment]
> Also like, its already done? See https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/tag/129.0.6668.70-3

Thats what ive been running?

**Comment by jamescraft10** [comment]
nvm i found it in the repo for the binarys
