### ISSUE TITLE
Potentially Hazardous LDFLAGS 

### ISSUE THREAD

**Issue by ilikenwf** [ungoogled-software/ungoogled-chromium-archlinux#287]
Some of us like to adjust our makepkg.conf flags and for 99% of packages this isn't an issue, but for chromium and some others this can sometimes cause issues, specifically "--no-omagic" - I find that if I add the following to the PKGBUILD just before we run make, it fixes what results in build failure. Even though this isn't necessarily a default LDFLAG, it may be handy to add this before building to prevent headaches as this caused one when I was debugging it?

`export LDFLAGS="${LDFLAGS//-Wl,-z,--no-omagic/}"`

**Comment by jstkdng** [comment]
uh, I thought this issue appeared due to a recent pacman upgrade and our CI was outdated but seems it is not.

Personally, I don't agree with supporting specific setups and we are better off supporting arch's defaults. @networkException up to you if you want to support this.

**Comment by networkException** [comment]
not really no, this isn't Gentoo :upside_down_face:

**Comment by PF4Public** [comment]
Did somebody say Gentoo? :penguin:
