### ISSUE TITLE
Some patches fail for 77.0.3865.75

### ISSUE THREAD

**Issue by jstkdng** [ungoogled-software/ungoogled-chromium-archlinux#30]
So far the following patches fail for this chromium version
- debian_buster/disable/chromeos.patch
- debian_buster/system/lcms.patch
- debian_buster/system/jsoncpp.patch

Also, some new patches are needed for archlinux

**Comment by jstkdng** [comment]
I've already added the archlinux patches, there are other ones, but those are in the inox patchset folder.
What is still bugging me is the chromeos.patch, is it needed for anything? is it still needed?
I've succesfully compiled chromium without those patches, but the doubt is still there.

**Comment by tangalbert919** [comment]
I was able to fix the patches in question, but it looks like we will need to start using those patches from Arch Linux now.

Still working on compiling this build successfully without looking at what @jstkdng did.

**Comment by nikolowry** [comment]
They've dropped Kiosk Next Home App, https://chromium-review.googlesource.com/c/chromium/src/+/1675589 -- so the checked-in `chromeos.patch` is no longer relevant and should be dropped as well.

**Comment by nikolowry** [comment]
`lcms.patch` just needs updated paths -- they did a reorg:

- first renamed from `ccodec_iccmodule.h`->`iccmodule.h`, https://pdfium.googlesource.com/pdfium/+/49d717afc97415c2e89cfc5f0dbb2294f11cecec
- then `pdfium/core/fxcodec/codec/iccmodule.h` was moved to  `pdfium/core/fxcodec/icc/iccmodule.h`, https://pdfium.googlesource.com/pdfium/+/49d717afc97415c2e89cfc5f0dbb2294f11cecec 

```patch
description: use system lcms for pdfium
author: Michael Gilbert <mgilbert@debian.org>

--- a/third_party/pdfium/core/fxcodec/icc/iccmodule.h
+++ b/third_party/pdfium/core/fxcodec/icc/iccmodule.h
@@ -14,7 +14,7 @@
 #include "core/fxcrt/fx_system.h"
 #include "third_party/base/span.h"
 
-#if defined(USE_SYSTEM_LCMS2)
+#if 1
 #include <lcms2.h>
 #else
 #include "third_party/lcms/include/lcms2.h"
```

**Comment by nikolowry** [comment]
The upstream code changes which `jsoncpp.patch` targets doesn't concern us because we are using system libs -- the patch just needs updating to deal with it those changes:

```patch
description: use system jsoncpp
author: Michael Gilbert <mgilbert@debian.org>

--- a/third_party/jsoncpp/BUILD.gn
+++ b/third_party/jsoncpp/BUILD.gn
@@ -4,51 +4,14 @@
 
 import("//testing/libfuzzer/fuzzer_test.gni")
 
-config("jsoncpp_config") {
-  include_dirs = [
-    "source/include",
-    "generated",
-  ]
+import("//build/config/linux/pkg_config.gni")
 
-  # TODO(crbug.com/983223): Update JsonCpp BUILD.gn to remove deprecated
-  # declaration flag.
-  # This temporary flag allowing clients to update to the new version, and then
-  # update to the new StreamWriter and CharReader classes.
-  if (!is_win || is_clang) {
-    cflags_cc = [ "-Wno-deprecated-declarations" ]
-  }
+pkg_config("jsoncpp_config") {
+    packages= [ "jsoncpp" ]
 }
 
-source_set("jsoncpp") {
-  sources = [
-    "generated/version.h",
-    "source/include/json/assertions.h",
-    "source/include/json/autolink.h",
-    "source/include/json/config.h",
-    "source/include/json/features.h",
-    "source/include/json/forwards.h",
-    "source/include/json/json.h",
-    "source/include/json/reader.h",
-    "source/include/json/value.h",
-    "source/include/json/writer.h",
-    "source/src/lib_json/json_reader.cpp",
-    "source/src/lib_json/json_tool.h",
-    "source/src/lib_json/json_value.cpp",
-    "source/src/lib_json/json_writer.cpp",
-  ]
-
+group("jsoncpp") {
   public_configs = [ ":jsoncpp_config" ]
-
-  defines = [
-    "JSON_USE_EXCEPTION=0",
-    "JSON_USE_NULLREF=0",
-  ]
-
-  include_dirs = [ "source/src/lib_json" ]
-
-  if (!is_win || is_clang) {
-    cflags_cc = [ "-Wno-implicit-fallthrough" ]
-  }
 }
 
 fuzzer_test("jsoncpp_fuzzer") {
```

**Comment by jstkdng** [comment]
so in the end the lcms patch is the only worth fixing, awesome!

**Comment by nikolowry** [comment]
@jstkdng I had to make some additional changes to achieve a successful build, but now I'm running into the same problems described at https://github.com/Eloston/ungoogled-chromium/issues/828. The changes were:

**Perfetto unbundle error**
After updating this repo's patches with the changes posted above, I got the following error:
```
  -> Configuring Chromium
ERROR Unresolved dependencies.
//third_party/perfetto/gn:zlib(//build/toolchain/linux/unbundle:default)
  needs //third_party/zlib:zlib_config(//build/toolchain/linux/unbundle:default)
```

I ended up jchanging `patches/debian_buster/system/zlib.patch:
```patch
description: use system zlib library instead of embedded lzma in courgette
author: Michael Gilbert <mgilbert@debian.org>

--- a/courgette/BUILD.gn
+++ b/courgette/BUILD.gn
@@ -60,7 +60,6 @@ static_library("courgette_lib") {
 
   deps = [
     "//base",
-    "//third_party/lzma_sdk",
   ]
 
   public_deps = [
@@ -81,7 +80,6 @@ source_set("courgette_common") {
   ]
   deps = [
     "//base",
-    "//third_party/lzma_sdk",
   ]
 }
 
--- a/courgette/crc.cc
+++ b/courgette/crc.cc
@@ -7,6 +7,8 @@
 #include <stdint.h>
 #include <stddef.h>
 
+#define COURGETTE_USE_CRC_LIB
+
 #ifdef COURGETTE_USE_CRC_LIB
 #  include "zlib.h"
 #else
--- a/third_party/perfetto/gn/BUILD.gn
+++ b/third_party/perfetto/gn/BUILD.gn
@@ -224,7 +224,6 @@ group("zlib") {
       "//buildtools:zlib",
     ]
   } else if (build_with_chromium) {
-    public_configs = [ "//third_party/zlib:zlib_config" ]
     public_deps = [
       "//third_party/zlib",
     ]
```

**One Euro Filter Missing StdLib Memory Header**
A new patch needs to be created from this upstream fix https://chromium-review.googlesource.com/c/chromium/src/+/1720637. The `one_euro_filter.patch` I applied:
```patch
--- a/third_party/one_euro_filter/src/one_euro_filter.h
+++ b/third_party/one_euro_filter/src/one_euro_filter.h
@@ -1,6 +1,8 @@
 #ifndef ONE_EURO_ONE_EURO_FILTER_H_
 #define ONE_EURO_ONE_EURO_FILTER_H_
 
+#include <memory>
+
 #include "low_pass_filter.h"
 
 namespace one_euro_filter {
```

**Remove third_party ICU headers from Native File System Usage Bubble View**
Updated `patches/debian_buster/system/icu.patch` to:
```patch
description: system icu
author: Michael Gilbert <mgilbert@debian.org>

--- a/net/BUILD.gn
+++ b/net/BUILD.gn
@@ -11,7 +11,6 @@ import("//build/config/ui.gni")
 import("//net/features.gni")
 import("//testing/libfuzzer/fuzzer_test.gni")
 import("//testing/test.gni")
-import("//third_party/icu/config.gni")
 import("//third_party/protobuf/proto_library.gni")
 import("//tools/grit/grit_rule.gni")
 import("//url/features.gni")
--- a/third_party/blink/renderer/platform/wtf/text/text_codec_utf8.cc
+++ b/third_party/blink/renderer/platform/wtf/text/text_codec_utf8.cc
@@ -503,7 +503,7 @@ TextCodec::EncodeIntoResult TextCodecUTF
 
   wtf_size_t i = 0;
   wtf_size_t previous_code_unit_index = 0;
-  bool is_error = false;
+  UBool is_error = false;
   while (i < length && encode_into_result.bytes_written < capacity &&
          !is_error) {
     UChar32 character;
--- a/v8/src/regexp/regexp-macro-assembler.cc
+++ b/v8/src/regexp/regexp-macro-assembler.cc
@@ -37,9 +37,9 @@ int RegExpMacroAssembler::CaseInsensitiv
 
 #ifdef V8_INTL_SUPPORT
   int32_t length = (int32_t)(byte_length >> 1);
-  icu::UnicodeString uni_str_1(reinterpret_cast<const char16_t*>(byte_offset1),
+  icu::UnicodeString uni_str_1(reinterpret_cast<const UChar*>(byte_offset1),
                                length);
-  return uni_str_1.caseCompare(reinterpret_cast<const char16_t*>(byte_offset2),
+  return uni_str_1.caseCompare(reinterpret_cast<const UChar*>(byte_offset2),
                                length, U_FOLD_CASE_DEFAULT) == 0;
 #else
   uc16* substring1 = reinterpret_cast<uc16*>(byte_offset1);
--- a/chrome/browser/ui/views/native_file_system/native_file_system_usage_bubble_view.cc
+++ b/chrome/browser/ui/views/native_file_system/native_file_system_usage_bubble_view.cc
@@ -24,9 +24,6 @@
 #include "content/public/browser/render_frame_host.h"
 #include "content/public/browser/render_process_host.h"
 #include "content/public/browser/web_contents.h"
-#include "third_party/icu/source/common/unicode/unistr.h"
-#include "third_party/icu/source/common/unicode/utypes.h"
-#include "third_party/icu/source/i18n/unicode/listformatter.h"
 #include "ui/base/l10n/l10n_util.h"
 #include "ui/gfx/paint_vector_icon.h"
 #include "ui/views/controls/button/image_button.h"
```

**System Harfbuzz Linker Errors**
A new patch needs to be created from this upstream fix https://chromium-review.googlesource.com/c/chromium/src/+/1715288. The `harfbuzz.patch` I applied:
```patch
--- a/third_party/harfbuzz-ng/BUILD.gn
+++ b/third_party/harfbuzz-ng/BUILD.gn
@@ -16,7 +16,10 @@
       "//third_party:freetype_harfbuzz",
       "//third_party/freetype:freetype_source",
     ]
-    packages = [ "harfbuzz" ]
+    packages = [
+      "harfbuzz",
+      "harfbuzz-subset",
+    ]
   }
 } else {
   config("harfbuzz_config") {
```

**Chromium Icon Sized at 22px No Longer Exists**
In `PKGBUILD`, delete `22` from the for loop in `package` at https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/master/PKGBUILD#L181

**Comment by jstkdng** [comment]
I ported the arch's chromium patches into my ungoogled chromium repo. So far so good. I'll make a new release with the new lcms patch.

**Comment by PF4Public** [comment]
> The upstream code changes which `jsoncpp.patch` targets doesn't concern us because we are using system libs -- the patch just needs updating to deal with those changes:
> 
> ```diff
> description: use system jsoncpp
> author: Michael Gilbert <mgilbert@debian.org>
> 
> --- a/third_party/jsoncpp/BUILD.gn
> +++ b/third_party/jsoncpp/BUILD.gn
> @@ -4,51 +4,14 @@
>  
>  import("//testing/libfuzzer/fuzzer_test.gni")
>  
> -config("jsoncpp_config") {
> -  include_dirs = [
> -    "source/include",
> -    "generated",
> -  ]
> +import("//build/config/linux/pkg_config.gni")
>  
> -  # TODO(crbug.com/983223): Update JsonCpp BUILD.gn to remove deprecated
> -  # declaration flag.
> -  # This temporary flag allowing clients to update to the new version, and then
> -  # update to the new StreamWriter and CharReader classes.
> -  if (!is_win || is_clang) {
> -    cflags_cc = [ "-Wno-deprecated-declarations" ]
> -  }
> +pkg_config("jsoncpp_config") {
> +    packages= [ "jsoncpp" ]
>  }
>  
> -source_set("jsoncpp") {
> -  sources = [
> -    "generated/version.h",
> -    "source/include/json/assertions.h",
> -    "source/include/json/autolink.h",
> -    "source/include/json/config.h",
> -    "source/include/json/features.h",
> -    "source/include/json/forwards.h",
> -    "source/include/json/json.h",
> -    "source/include/json/reader.h",
> -    "source/include/json/value.h",
> -    "source/include/json/writer.h",
> -    "source/src/lib_json/json_reader.cpp",
> -    "source/src/lib_json/json_tool.h",
> -    "source/src/lib_json/json_value.cpp",
> -    "source/src/lib_json/json_writer.cpp",
> -  ]
> -
> +group("jsoncpp") {
>    public_configs = [ ":jsoncpp_config" ]
> -
> -  defines = [
> -    "JSON_USE_EXCEPTION=0",
> -    "JSON_USE_NULLREF=0",
> -  ]
> -
> -  include_dirs = [ "source/src/lib_json" ]
> -
> -  if (!is_win || is_clang) {
> -    cflags_cc = [ "-Wno-implicit-fallthrough" ]
> -  }
>  }
>  
>  fuzzer_test("jsoncpp_fuzzer") {
> ```

We're reinventing the same wheel with this patching :) I've rewritten this patch a few days ago :)

I'm thinking now of dropping all my patches in my overlay, using ungoogled-archlinux as an additional source and contributing directly here… I'm undecided yet…

**Comment by nikolowry** [comment]
@jstkdng I didn't realize you had already pushed your changes needed for 77.0.3865.90 up to your fork -- I had just been experimenting locally and was reporting progress as I went. 

From looking at your patches, the big one that seems to be missing from my builds that were leading to an "Aw Snap" is https://github.com/jstkdng/ungoogled-chromium-archlinux/blob/master/patches/arch_linux/fix-wrong-string-initialization-in-LinkedHashSet.patch. But I also see you omitted both the `jsoncpp.patch` and `lcms.patch` and had some minor differences as well.

Regardless, I just successfully built your repo and am not experiencing any more segfaults. 

cc @PF4Public

**Comment by jstkdng** [comment]
@nikolowry 
seriously what kind of computer do you have for you to be able to compile chromium as easy as that.
Oh, and btw,I also replaced the debian's icu and zlib patches for arch specific ones.
Will add the lcms patch on the next release of chromium, too lazy to compile again.

**Comment by nikolowry** [comment]
![Screenshot from 2019-09-22 23-30-07](https://user-images.githubusercontent.com/597310/65400576-08d9d200-dd91-11e9-98c6-eced3221cbb7.png)

@jstkdng a fresh compile takes me roughly an hour -- and earlier between errors I was running `makepkg --nodeps --noextract --noprepare -f` and manually editing `src/chromium-77.0.3865.90/**/*` to avoid starting from scratch.

**Comment by jstkdng** [comment]
@nikolowry 
wow, that's some serious dedication.
It takes ~2 hours for my 3400G to clean compile chromium, before it took ~6 hours in my 200GE, that was a huge update for me.

**Comment by TeslaBargain** [comment]
I'm sorry for intruding, I have just discovered this yesterday and I'm not a developer but only a Manjaro GNOME user:

So did I understand this right that @jstkdng's fork is ready to properly build 77.0.3865.90 but the official PKGBUILD is not yet?

And are there any plans for the AUR package maintenance to get sorted, because there are now three separate AUR packages for ungoogled-chromium with the one referenced here on github being maintained by @seppia ?

The current AUR situation and the fact that there is at least one fork of the official github repo is pretty confusing, and obviously it makes more sense to have a properly maintained AUR package than having to fetch the PKBUILD from github manually.

**Comment by jstkdng** [comment]
@TeslaBargain 
yeah, my fork is all nice and ready, I won't PR because my fork has diverged a lot from upstream, particularly because of this [PR](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/commit/943c4a3abc7a6d88a01bd9d51bdce9b9919064c2).
It seems upstream is going for a more automated approach and I'm going for a more manual approach, PRing would mean throwing out of other people's work and time invested in this project.
Also, it seems this issue was fixed by @nikolowry , make another issue if you want to continue this discussion.
