### ISSUE TITLE
Add back VA-API support

### ISSUE THREAD

**Issue by TeslaBargain** [ungoogled-software/ungoogled-chromium-archlinux#33]
According to a comment in the AUR for [**ungoogled-chromium**](https://aur.archlinux.org/packages/ungoogled-chromium/) this PKBUILD formerly included [**vaapi-fix.patch**](https://aur.archlinux.org/cgit/aur.git/tree/vaapi-fix.patch?h=chromium-vaapi) but it has been dropped for unknown reasons?

Please bring back support for HW acceleration, because it really makes no sense to miss out on that very important feature and only feeds the need for more than one ungoogled-chromium build when we could have an all-in-one AUR package instead.

**Comment by howaboutsynergy** [comment]
lookslike it will be back when PR #32  lands: https://github.com/ungoogled-software/ungoogled-chromium-archlinux/pull/32/files#diff-14e5dc0abf7e8a4b1863c02864ca744d

**Comment by wchen342** [comment]
I checked the PKGBUILD for 77.0.3865.120-1 in seppia's package and `vaapi.patch` is there, so I guess this is solved for now?

**Comment by TeslaBargain** [comment]
Can someone confirm that HW video acceleration is working with the build from seppia's package?

I'm currently using the [binary package](https://github.com/jstkdng/ungoogled-chromium-archlinux) made by @jstkdng.

**Comment by Scrumplex** [comment]
> Can someone confirm that HW video acceleration is working with the build from seppia's package?
> 
> I'm currently using the [binary package](https://github.com/jstkdng/ungoogled-chromium-archlinux) made by @jstkdng

When playing a YouTube video on X11. The CPU usage is very low for chromium (around 4%). 

```
Data exported | 2019-10-19T11:05:05.013Z
-- | --
Chrome version | Chrome/77.0.3865.120
Operating system | Linux 5.3.7-arch1-1-ARCH
Software rendering list URL | https://chromium.9oo91esource.qjz9zk/chromium/src/+/416d6d8013e9adb6dd33b0c12e7614ff403d1a94/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.9oo91esource.qjz9zk/chromium/src/+/416d6d8013e9adb6dd33b0c12e7614ff403d1a94/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | unknown hash
2D graphics backend | Skia/77 a10014304cba4f24b7af17191f59490faa8aee77
Command Line | /usr/lib/chromium/chromium --flag-switches-begin --enable-features=WebUIDarkMode,CheckerImaging,MarkHttpAs,ScrollAnchorSerialization,brotli-encoding --force-dark-mode --enable-quic --enable-tcp-fastopen -–enable-gpu-rasterization --force-gpu-rasterization --enable-native-gpu-memory-buffers --enable-oop-rasterization --ignore-gpu-blacklist --use-skia-deferred-display-list --enable-surfaces-for-videos -–enable-zero-copy --enable-fast-unload --save-page-as-mhtml --enable-smooth-scrolling --site-per-process --enable-http-form-warning --enable-tab-audio-muting --history-entry-requires-user-gesture --enable-scroll-anchoring --flag-switches-end --flag-switches-begin --enable-experimental-web-platform-features --flag-switches-end --file-url-path-alias=/gen=/usr/lib/chromium/gen
```

**Comment by Master0ne** [comment]
@Scrumplex that data is not really telling anything. I guess this is what it is supposed to look like when going to 'chrome://gpu`:

![hardware_accelerated](https://user-images.githubusercontent.com/8912853/67155945-881edf00-f318-11e9-8030-ee15db159272.png)

**Comment by jstkdng** [comment]
actually, better info would be the decoder you get when playing a video.
1. play a video
2. go to chrome://media-internals
3. Collapse the list and look at the video decoder, if it says mojo video decoder then its all good. If you get ffmpegvideodecoder then hw accel is broken.

**Comment by TeslaBargain** [comment]
@jstkdng, here `chrome://media-internals` shows `dav1d` so I guess it should be working correctly (with your ungoogled-chromium build), having Intel Graphics HD 620 properly set up.

**Comment by jstkdng** [comment]
@TeslaBargain you should be all good then.

**Comment by jstkdng** [comment]
#79 should have fixed this issue. Reopen if it still isn't working.
