### ISSUE TITLE
ungoogled-chromium-ozone with Wayland and VAAPI support?

### ISSUE THREAD

**Issue by Master0ne** [ungoogled-software/ungoogled-chromium-archlinux#42]
I'm using GNOME on Wayland with fractional scaling set to 150% to make my external 4k screen usable, but [fractional scaling breaks rendering of apps running on Xwayland](https://bbs.archlinux.org/viewtopic.php?pid=1873519#p1873519) (like ungoogled-chromium) and VAAPI doesn't work on Xwayland either.

But there is [chromium-ozone](https://aur.archlinux.org/packages/chromium-ozone/) which is Chromium built with patches for Wayland support via Ozone.

Any chances of an ungoogled-chromium-ozone with Wayland and VAAPI support?

**Comment by jstkdng** [comment]
Checking the ```chromium-ozone``` PKGBUILD, the only change are the build flags, you could change the ```archlinux.flags.gn``` file and add the flags from chromium-ozone. Then hope for it to compile.

**Comment by Eloston** [comment]
If it works, would it make sense to add a toggle in the PKGBUILD to enable Ozone? Less preferably, we could add a new branch named `ozone` or something.

**Comment by Master0ne** [comment]
I received the following feedback from @hedgepigdaniel concerning chromium-ozone and VAAPI support in the AUR comments:

>The VAAPI patches for the X11 builds are not compatible because Ozone uses a significantly different codepath for video decoding generally.
> 
> I don't believe the Igalia team working on this have made desktop VAAPI a priority, although it seems they have video acceleration via v4l2 working for embedded devices: https://github.com/OSSystems/meta-browser/tree/master/recipes-browser/chromium
> 
> I've personally tried to make it work. A minor fox is required to make it build with the use_vaapi flag, but then I couldn't find a combination of minigbm, libdrm etc that made the video acceleration actually happen.

HW accelerated video is definitely nice to have (I really see a huge difference here on my laptop), but the **ungoogling** is way more important of course!

**Comment by hedgepigdaniel** [comment]
take what I said with a grain of salt - I'm not very familiar with the patches to start with

**Comment by jstkdng** [comment]
An ozone branch should be created in the next few weeks. Also, no answer from OP for some time now. Closing.
