### ISSUE TITLE
PKGBUILD URLS to chromium_version.txt and revision.txt not working

### ISSUE THREAD

**Issue by hchr** [ungoogled-software/ungoogled-chromium-archlinux#43]
https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/master/PKGBUILD

curl -sL https://raw.githubusercontent.com/Eloston/ungoogled-chromium/${_ungoogled_version}/chromium_version.txt
404: Not Found

curl -sL https://raw.githubusercontent.com/Eloston/ungoogled-chromium/${_ungoogled_version}/revision.txt
404: Not Found

When adding /master/ after ungoogled-chromium/
it works.

curl -sL https://raw.githubusercontent.com/Eloston/ungoogled-chromium/master/${_ungoogled_version}/chromium_version.txt
78.0.3904.108

curl -sL https://raw.githubusercontent.com/Eloston/ungoogled-chromium/master/${_ungoogled_version}/revision.txt
1

**Comment by Eloston** [comment]
I don't have any issues with those URLs based on the PKGBUILD in `master` after setting `_ungoogled_version` to the value shown in the PKGBUILD. Perhaps this was a temporary issue?

**Comment by hchr** [comment]
Yes, this is invalid. Sorry for the noise.
