### ISSUE TITLE
VAAPI Error

### ISSUE THREAD

**Issue by wchen342** [ungoogled-software/ungoogled-chromium-archlinux#48]
I had this issue on one of my machines (Xeon E5/GTX) that `ungoogled-chromium` will crash on start. It happens with both `.117` and `.130` The error message is `ERROR:vaapi_wrapper.cc(422)] vaInitialize failed (ignore if using Wayland desktop environment, refer:(Github)akarshanbiswas/chromium-vaapi/issues/7): unknown libva error`.

Strangely enough, it doesn't crash on other machines (i7+Integrated video card, i5+Nvidia Optimus
)

A workaround has been provided on AUR, that is to set `LIBVA_DRIVER_NAME=nouveau`. Actually it doesn't matter what the variable is set to, as long as it exists eberything is fine.

**Comment by jstkdng** [comment]
Nvidia drivers have no support for vaapi, the intel driver does, you have to use libva-vdpau-driver-chromium

**Comment by wchen342** [comment]
@jstkdng 

Weird, that didn't work for me. It actually makes things worse. After installing the package it crashes 6 times instead of once:
```
Received signal 11 SEGV_MAPERR 000000000000
#0 0x07976fef373a <unknown>
  r8: 00000000ffffffff  r9: 0000735e69587ef0 r10: 00006fbc3a0d0207 r11: 0000000000000006
 r12: 0000735e69588850 r13: 0000735e6958881c r14: 0000000000000000 r15: 0000735e69588830
  di: 0000000000000000  si: 00003e424d126940  bp: 0000735e69588500  bx: 0000000000000000
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 0000735e69588308
  ip: 00006fbc3f0a11e5 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[0212/165343.624249:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
Received signal 11 SEGV_MAPERR 000000000000
#0 0x0f46130a173a <unknown>
  r8: 00000000ffffffff  r9: 00007530afd374a0 r10: 0000679224e18207 r11: 0000000000000006
 r12: 00007530afd37e00 r13: 00007530afd37dcc r14: 0000000000000000 r15: 00007530afd37de0
  di: 0000000000000000  si: 00002fa27e44a9c0  bp: 00007530afd37ab0  bx: 0000000000000000
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 00007530afd378b8
  ip: 0000679229de91e5 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[0212/165343.726891:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 2 time(s)
Received signal 11 SEGV_MAPERR 000000000000
#0 0x03d58837c73a <unknown>
  r8: 00000000ffffffff  r9: 000070f501da5ba0 r10: 00006176dbe1c207 r11: 0000000000000006
 r12: 000070f501da6500 r13: 000070f501da64cc r14: 0000000000000000 r15: 000070f501da64e0
  di: 0000000000000000  si: 00000cd915a8a940  bp: 000070f501da61b0  bx: 0000000000000000
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 000070f501da5fb8
  ip: 00006176e0ded1e5 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[0212/165343.826318:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 3 time(s)
Received signal 11 SEGV_MAPERR 000000000000
#0 0x059e0bb1e73a <unknown>
  r8: 00000000ffffffff  r9: 00007cb44f9efec0 r10: 00006893d49d7207 r11: 0000000000000006
 r12: 00007cb44f9f0820 r13: 00007cb44f9f07ec r14: 0000000000000000 r15: 00007cb44f9f0800
  di: 0000000000000000  si: 00002632e13cf940  bp: 00007cb44f9f04d0  bx: 0000000000000000
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 00007cb44f9f02d8
  ip: 00006893d99a81e5 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[0212/165343.935244:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 4 time(s)
Received signal 11 SEGV_MAPERR 000000000000
#0 0x05a9e183373a <unknown>
  r8: 00000000ffffffff  r9: 00007373753037e0 r10: 000066235a807207 r11: 0000000000000006
 r12: 0000737375304140 r13: 000073737530410c r14: 0000000000000000 r15: 0000737375304120
  di: 0000000000000000  si: 00002708cdbf3940  bp: 0000737375303df0  bx: 0000000000000000
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 0000737375303bf8
  ip: 000066235f7d81e5 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[0212/165344.031582:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 5 time(s)
Received signal 11 SEGV_MAPERR 000000000000
#0 0x06623541273a <unknown>
  r8: 00000000ffffffff  r9: 000073cf43d680f0 r10: 000061042fb66207 r11: 0000000000000006
 r12: 000073cf43d68a50 r13: 000073cf43d68a1c r14: 0000000000000000 r15: 000073cf43d68a30
  di: 0000000000000000  si: 000000320172e940  bp: 000073cf43d68700  bx: 0000000000000000
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 000073cf43d68508
  ip: 0000610434b371e5 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[0212/165344.120254:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 6 time(s)
[0212/165344.120309:FATAL:gpu_data_manager_impl_private.cc(990)] The display compositor is frequently crashing. Goodbye.
#0 0x0373b78dc73a <unknown>

Received signal 6
#0 0x0373b78dc73a <unknown>
  r8: 0000000000000000  r9: 00006c470b4c3280 r10: 0000000000000008 r11: 0000000000000246
 r12: 0000000000000078 r13: 00006c470b4c4550 r14: 00006c47153a25e0 r15: 00006c470b4c4548
  di: 0000000000000002  si: 00006c470b4c3280  bp: 00006c470b4c34d0  bx: 00006c470b4c6700
  dx: 0000000000000000  ax: 0000000000000000  cx: 00006c471521dce5  sp: 00006c470b4c3280
  ip: 00006c471521dce5 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

Unset the environment variable and the same.

**Comment by jstkdng** [comment]
>Xeon E5/GTX
You have an NVIDIA gpu right, are you using the propietary drivers?

**Comment by wchen342** [comment]
Yeah I'm using propietary drivers cause I need CUDA.

**Comment by jstkdng** [comment]
hmm, you are using this repositories PKGBUILD right? It is using an old vaapi patch, you could try my package which have the same patch as chromium-vaapi: https://download.opensuse.org/repositories/home:/justkidding:/arch/standard/x86_64/ungoogled-chromium-80.0.3987.100-1-x86_64.pkg.tar.xz
also, combine it with this libva-vdpau-driver-chromium which contains another patch for chromium > 79 : https://github.com/jstkdng/libva-vdpau-driver-chromium

**Comment by alium** [comment]
for me (RYZEN 5 3400G) is in chromium 80 VAAPI really broken...
![Screenshot_20200216_161402](https://user-images.githubusercontent.com/1759414/74607276-dcc04400-50d7-11ea-90e3-b56979677583.png)

i used ungoogled chromium  version 79, and video worked perfectly, after update to version 80 (newest what i tested: https://download.opensuse.org/repositories/home:/justkidding:/arch/standard/x86_64/ungoogled-chromium-80.0.3987.106-1-x86_64.pkg.tar.xz) is video playback for 720p broken.
same broken video i can see with chromium-vaapi  80.0.3987.100 (from AUR).
only was works is chromium (without HW decode acceleration)

I will now test another mesa version (have installed actually mesa 20.1.0-devel-git), maybe is not bug of chromium

**Comment by jstkdng** [comment]
@alium 
I also have a 3400G and using mesa-git really broke video playback. Switch to regular mesa. Also, please open issues related to my stuff in this repo: https://github.com/jstkdng/ungoogled-chromium-archlinux

**Comment by alium** [comment]
ok, so i found that problem....

VAAPI is not broken. this broking makes enabled rasterization. If i switch to software only, video play clearly again.

btw. i tested all on my old laptop with Intel Haswell and Archlinux too, so no bug via upgrade system or chromium.

**Comment by Ph0rk0z** [comment]
Used the latest build on arch and this still happens to me:

ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)

chrome://media-internals says "VDA Error 4" and drops back to FFmpeg when I play H264 youtube.

I have a haswell i7 (igpu only) and arch on this machine. So maybe the problem isn't fixed? I ended up going with the 3rd party build of 4044.129 because it would take hours to compile with this CPU. 

I could try a git mesa build if you think it's intel's fault.

**Comment by jstkdng** [comment]
Good to know it works for you m8.

**Comment by Rowisi** [comment]
Me too I have built @jstkdng repo and Vaapi works fine thanks to the patches he added.

**Comment by Ph0rk0z** [comment]
Hey, does this mean its fixed in the main repo since we're closing the issue and all?

**Comment by wchen342** [comment]
This should have been fixed since last version. If you still come accross problems please open a new issue.
