### ISSUE TITLE
Fix debug builds

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-archlinux#58]
Solution proposed here (and context of the issue here): https://github.com/ungoogled-software/ungoogled-chromium-archlinux/pull/55#issuecomment-586633760

**Comment by jstkdng** [comment]
Took a while to solve this, but oh well.
Instead of just editing all files that require the fuzzer header, just install it.
I just created a package for that: https://aur.archlinux.org/packages/libfuzzer-header/
Just install it and all should be ok.

**Comment by wchen342** [comment]
@jstkdng Is the header the same across all versions? I'm asking because the package doesn't say which libBuzz version it is for. I think it will be better if the version is specified.

**Comment by jstkdng** [comment]
In order to make that package less niche I'd figure I just include all the compiler-rt headers that aren't included in the base package. I made another package with a more descriptive name and also includes all compiler-rt headers: https://aur.archlinux.org/packages/compiler-rt-headers/
Though, the ideal solution would be to ask arch upstream to add them to the official compiler-rt package, as their PKGBUILD already builds them, just chose to not install them.

**Comment by jstkdng** [comment]
Update: how funny, the moment I create my packages arch upstream adds the required headers to the compiler-rt package. Guess this change solves this problem altogether.
```sh
~ pacman -Ql compiler-rt | grep include
compiler-rt /usr/include/
compiler-rt /usr/include/fuzzer/
compiler-rt /usr/include/fuzzer/FuzzedDataProvider.h
compiler-rt /usr/include/profile/
compiler-rt /usr/include/profile/InstrProfData.inc
compiler-rt /usr/include/sanitizer/
compiler-rt /usr/include/sanitizer/allocator_interface.h
compiler-rt /usr/include/sanitizer/asan_interface.h
compiler-rt /usr/include/sanitizer/common_interface_defs.h
compiler-rt /usr/include/sanitizer/coverage_interface.h
compiler-rt /usr/include/sanitizer/dfsan_interface.h
compiler-rt /usr/include/sanitizer/hwasan_interface.h
compiler-rt /usr/include/sanitizer/linux_syscall_hooks.h
compiler-rt /usr/include/sanitizer/lsan_interface.h
compiler-rt /usr/include/sanitizer/msan_interface.h
compiler-rt /usr/include/sanitizer/netbsd_syscall_hooks.h
compiler-rt /usr/include/sanitizer/scudo_interface.h
compiler-rt /usr/include/sanitizer/tsan_interface.h
compiler-rt /usr/include/sanitizer/tsan_interface_atomic.h
compiler-rt /usr/include/sanitizer/ubsan_interface.h
compiler-rt /usr/include/xray/
compiler-rt /usr/include/xray/xray_interface.h
compiler-rt /usr/include/xray/xray_log_interface.h
compiler-rt /usr/include/xray/xray_records.h
```

**Comment by wchen342** [comment]
That explains why I didn't run into any errors when building a debug build yesterday. Let me test on newest Arch again and if that works then this should be considered solved.

**Comment by wchen342** [comment]
Ok this problem is gone. There are several additional "symbols not found" error but I think it's better open a new issue cause those should be patched somehow.
