### ISSUE TITLE
Shared libraries 'libre2.so.6' cannont be opened

### ISSUE THREAD

**Issue by pluja** [ungoogled-software/ungoogled-chromium-archlinux#77]
`/usr/lib/chromium/chromium: error while loading shared libraries: libre2.so.6: cannot open shared object file: No such file or directory`

That's the error i'm getting. Can't find anything about this libraries on the internet. This started happening with latest run of `pacman -Syu`

**Comment by pluja** [comment]
Making a `find / | grep "libre2.so"` shows that I have the libre2.so.7 installed, this might be the issue. I created a symlink from `libre2.so.6 -> libre2.so.7` but is still not working.

**Comment by Rowisi** [comment]
Library versions are changed to indicate the interface has changed in an incompatible way.  Symlinking to the old version ignores that change resulting in undefined behavior.

There are 2 safe ways to fix this. downgrade `re2` or upgrade chromium.

**Comment by wchen342** [comment]
You need to rebuild everytime a library UC linked to has a major version upgrade.

**Comment by Msouza91** [comment]
Well, build is failing with the new lib, tried twice today...
A binary package should be high priority rn IMHO.

**Comment by jstkdng** [comment]
@Msouza91 
we are tackling that right now
you can get a working binary from here: https://download.opensuse.org/repositories/home:/justkidding:/arch/standard/x86_64/ungoogled-chromium-81.0.4044.138-3-x86_64.pkg.tar.xz

**Comment by Eloston** [comment]
Maybe we should add this patch for now? https://github.com/Eloston/ungoogled-chromium/issues/1031#issuecomment-626258413

**Comment by wchen342** [comment]
@Eloston It is already been added in #78.
