### ISSUE TITLE
A new version of Vaapi came out:

### ISSUE THREAD

**Issue by ViNi-Arco** [ungoogled-software/ungoogled-chromium-archlinux#89]
A new version of the Vaapi patch came out, could you use it?
https://chromium-review.googlesource.com/c/chromium/src/+/2062356

**Comment by ViNi-Arco** [comment]
anyway, I took the liberty of copying the patch on the page, here's:
[enable-vaapi.txt](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/files/4873812/enable-vaapi.txt)
just change the `.txt` to `.patch`

**Comment by jstkdng** [comment]
I've updated the patch, can you test? https://repo.vin.ovh/arch/x86_64/test/ungoogled-chromium-83.0.4103.116-2-x86_64.pkg.tar.zst

**Comment by ViNi-Arco** [comment]
@jstkdng I'll test it, give me a few minutes and I'll give you the answer

**Comment by jstkdng** [comment]
also, the "new patch" does the same as the old patch. The only thing that's different is the patches on the browser flags.

**Comment by ViNi-Arco** [comment]
@jstkdng  It worked as well as the old patch, I tested it and didn't hear any problems, for more information I tested it on Nvidia driver 450.36.06

**Comment by ViNi-Arco** [comment]
> also, the "new patch" does the same as the old patch. The only thing that's different is the patches on the browser flags.

uhm this demonstrates that the patch is already stable and needed a few adjustments, since they sent the request upstream, it would be great news for them to accept the patch officially

**Comment by ViNi-Arco** [comment]
More tests and so far no problems!

**Comment by jstkdng** [comment]
chromium already supports vaapi via the `enable_vaapi` flag, that patch only fixes a problem related to vp9 on intel graphics. Nvidia doesnt support vaapi, only vdpau, the fact that it worked for you on nvidia is because of a different patch here and not the one from the url you send.

**Comment by ViNi-Arco** [comment]
> chromium already supports vaapi via the enable_vaapi flag, that patch only fixes a problem related to vp9 on intel graphics. Nvidia doesnt support vaapi, only vdpau, the fact that it worked for you on nvidia is because of a different patch here and not the one from the url you send.

:facepalm: :facepalm: sorry for my mistake, it was on my desktop and I tested it, I have a notebook with integrated Intel graphics, and a dedicated AMD GPU I will test on it

**Comment by ViNi-Arco** [comment]
@jstkdng I tested it on my Dell Inspiron 5559 with Intel Graphics 540 with Mesa 20.1.2, I can't see any difference compared to the previous patch, and there were no regressions.

You have the freedom to decide whether to use this patch, whether yes or no! can close this problem

**Comment by jstkdng** [comment]
yeah, will check if it is worth it. Closing.
