### ISSUE TITLE
libre2.so.7 missing, unable to start UC

### ISSUE THREAD

**Issue by gothmog123** [ungoogled-software/ungoogled-chromium-archlinux#90]
the terminal message is:

/usr/lib/chromium/chromium: error while loading shared libraries: libre2.so.7: cannot open shared object file: No such file or directory

**Comment by jstkdng** [comment]
Yeah, re2 was recently updated, you can get a working binary here: https://download.opensuse.org/repositories/home:/justkidding:/arch/standard/x86_64/ungoogled-chromium-83.0.4103.116-2-x86_64.pkg.tar.zst
