### ISSUE TITLE
Why 806 MB extraction takes about a half one hour

### ISSUE THREAD

**Issue by abdulbadii** [ungoogled-software/ungoogled-chromium-archlinux#93]
Just a simple:
`-> Extracting chromium-84.0.4147.89.tar.xz with bsdtar`
Why'd it take more than half an hour, any useful tips/tricks ?

**Comment by lahwaacz** [comment]
Because the extracted content has more than 6.8 GB and over 400k files, so if you have a slow disk or a slow CPU, it's going to take a while...

**Comment by wchen342** [comment]
Also something worth checking is what % of memory is used. If your memory is not large enough and a lot of swap happens it will slow things down greatly.

**Comment by abdulbadii** [comment]
Thanks!
simply my ancient laptop proved it.
