### ISSUE TITLE
Launcing failure; error while loading shared libraries: libre2.so.7:

### ISSUE THREAD

**Issue by abdulbadii** [ungoogled-software/ungoogled-chromium-archlinux#94]
As executed **ungoogled-chromium version 83.0.4103.116-2** in https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/archlinux/83.0.4103.116-2
It was interrupted,
`/usr/lib/chromium/chromium: error while loading shared libraries: libre2.so.7: cannot open shared object file`

It's not installed as,
```
$ find /usr -regex '.*libre2\.so.*'
find: ‘/usr/lib/firmware/b43’: Permission denied
find: ‘/usr/lib/firmware/b43legacy’: Permission denied
/usr/lib/libre2.so
/usr/lib/libre2.so.8
/usr/lib/libre2.so.8.0.0

```
How to install it and to resolve this?

**Comment by wchen342** [comment]
You need to update to a new version and recompile the package.

**Comment by abdulbadii** [comment]
It is the latest as was said: n https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/archlinux/83.0.4103.116-2

**Comment by wchen342** [comment]
The binaries are contributed by third party contributors so they are not always up to date. You can get a latest version from @jstkdng's OBS repository though: [https://download.opensuse.org/repositories/home:/justkidding:/arch/standard/x86_64/ungoogled-chromium-84.0.4147.89-1-x86_64.pkg.tar.zst](https://download.opensuse.org/repositories/home:/justkidding:/arch/standard/x86_64/ungoogled-chromium-84.0.4147.89-1-x86_64.pkg.tar.zst)

**Comment by wchen342** [comment]
@jstkdng Actually is it possible to make an Action that pulls from your OBS and make a PR to `-binaries`?

**Comment by abdulbadii** [comment]
Latest on link works. Thanks.

**Comment by jstkdng** [comment]
@wchen342 I'm not sure tbh, might have to think a solution if really required. In the meantime I'll just PR my builds to -binaries.
