### ISSUE TITLE
Vaapi wrapper error

### ISSUE THREAD

**Issue by FilipLitwora** [ungoogled-software/ungoogled-chromium-archlinux#99]
Hello,
I downloaded ungoogled-chromium from AUR, and I get this error sometimes after loading a site, and sometimes even before searching anything. 
```
[43913:43913:0823/133934.661580:ERROR:vaapi_wrapper.cc(514)] vaInitialize failed: unknown lib
zsh: segmentation fault (core dumped)  chromium
```
I'm using Xorg and GTX 950 proprietary

**Comment by jstkdng** [comment]
Do you have this package installed? https://aur.archlinux.org/packages/libva-vdpau-driver-chromium/
Only way to have vaapi with propietary nvidia drivers.

**Comment by FilipLitwora** [comment]
Just installed this package, now I get this error: 
```
broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
```

**Comment by jstkdng** [comment]
Is it crashing now? Does vaapi work?

**Comment by FilipLitwora** [comment]
Yeah, its crashing almost immediately after opening with this error: `[8973:8982:0823/210558.735325:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)`

**Comment by jstkdng** [comment]
Are you using any flags?

**Comment by FilipLitwora** [comment]
Nope

**Comment by jstkdng** [comment]
Add this flag to your `~/.config/chromium-flags.conf` file
`--ignore-gpu-blacklist`

**Comment by FilipLitwora** [comment]
Still same error

**Comment by jstkdng** [comment]
I've been looking around and that other chromium based projects are having the same problem as you. Could be useful to troubleshoot. You could also try to build UC without the `use_vaapi=true` flag.

**Comment by FilipLitwora** [comment]
Sorry, I don't have another 2.5 h to compile... Nevertheless, thanks for help

**Comment by jstkdng** [comment]
1 month without update from op, closing.
